// Generated by scripts/i18n_build.mjs. Do not edit by hand.
//
// Part of the generated src/ui/i18n.resolved.generated/ directory: one dense
// locale slice per file (each `: EnTranslations` = typeof en, so tsc red-fails a
// missing or renamed key), a back-compat barrel (index.ts) that re-exports every
// slice and assembles the runtime `translations` map, per-locale lazy loaders
// (loaders.ts), and the pending set (pending.ts). Regenerate with
// `npm run i18n:build` (also wired into `npm run build` and `pretest`).
// Reproducibility is checked by tests/i18n_resolved_equivalence.test.ts.

export const pending: Record<string, readonly string[]> = {
  "es": [
    "hudChrome.ads.adNotAvailable",
    "hudChrome.ads.boostOfferTitle",
    "hudChrome.ads.earnedBoost",
    "hudChrome.ads.earnedRevive",
    "hudChrome.ads.reviveReady",
    "hudChrome.ads.skip",
    "hudChrome.ads.watchForBoost",
    "hudChrome.ads.watchForRevive",
    "hudChrome.donate.close",
    "hudChrome.donate.copied",
    "hudChrome.donate.copy",
    "hudChrome.donate.intro",
    "hudChrome.donate.pixLabel",
    "hudChrome.donate.qrAlt",
    "hudChrome.donate.thanks",
    "hudChrome.donate.title"
  ],
  "es_ES": [
    "hudChrome.ads.adNotAvailable",
    "hudChrome.ads.boostOfferTitle",
    "hudChrome.ads.earnedBoost",
    "hudChrome.ads.earnedRevive",
    "hudChrome.ads.reviveReady",
    "hudChrome.ads.skip",
    "hudChrome.ads.watchForBoost",
    "hudChrome.ads.watchForRevive",
    "hudChrome.donate.close",
    "hudChrome.donate.copied",
    "hudChrome.donate.copy",
    "hudChrome.donate.intro",
    "hudChrome.donate.pixLabel",
    "hudChrome.donate.qrAlt",
    "hudChrome.donate.thanks",
    "hudChrome.donate.title"
  ],
  "fr_FR": [
    "hudChrome.ads.adNotAvailable",
    "hudChrome.ads.boostOfferTitle",
    "hudChrome.ads.earnedBoost",
    "hudChrome.ads.earnedRevive",
    "hudChrome.ads.reviveReady",
    "hudChrome.ads.skip",
    "hudChrome.ads.watchForBoost",
    "hudChrome.ads.watchForRevive",
    "hudChrome.donate.close",
    "hudChrome.donate.copied",
    "hudChrome.donate.copy",
    "hudChrome.donate.intro",
    "hudChrome.donate.pixLabel",
    "hudChrome.donate.qrAlt",
    "hudChrome.donate.thanks",
    "hudChrome.donate.title"
  ],
  "fr_CA": [
    "hudChrome.ads.adNotAvailable",
    "hudChrome.ads.boostOfferTitle",
    "hudChrome.ads.earnedBoost",
    "hudChrome.ads.earnedRevive",
    "hudChrome.ads.reviveReady",
    "hudChrome.ads.skip",
    "hudChrome.ads.watchForBoost",
    "hudChrome.ads.watchForRevive",
    "hudChrome.donate.close",
    "hudChrome.donate.copied",
    "hudChrome.donate.copy",
    "hudChrome.donate.intro",
    "hudChrome.donate.pixLabel",
    "hudChrome.donate.qrAlt",
    "hudChrome.donate.thanks",
    "hudChrome.donate.title"
  ],
  "en_CA": [],
  "it_IT": [
    "hudChrome.ads.adNotAvailable",
    "hudChrome.ads.boostOfferTitle",
    "hudChrome.ads.earnedBoost",
    "hudChrome.ads.earnedRevive",
    "hudChrome.ads.reviveReady",
    "hudChrome.ads.skip",
    "hudChrome.ads.watchForBoost",
    "hudChrome.ads.watchForRevive",
    "hudChrome.donate.close",
    "hudChrome.donate.copied",
    "hudChrome.donate.copy",
    "hudChrome.donate.intro",
    "hudChrome.donate.pixLabel",
    "hudChrome.donate.qrAlt",
    "hudChrome.donate.thanks",
    "hudChrome.donate.title"
  ],
  "de_DE": [
    "hudChrome.ads.adNotAvailable",
    "hudChrome.ads.boostOfferTitle",
    "hudChrome.ads.earnedBoost",
    "hudChrome.ads.earnedRevive",
    "hudChrome.ads.reviveReady",
    "hudChrome.ads.skip",
    "hudChrome.ads.watchForBoost",
    "hudChrome.ads.watchForRevive",
    "hudChrome.donate.close",
    "hudChrome.donate.copied",
    "hudChrome.donate.copy",
    "hudChrome.donate.intro",
    "hudChrome.donate.pixLabel",
    "hudChrome.donate.qrAlt",
    "hudChrome.donate.thanks",
    "hudChrome.donate.title"
  ],
  "zh_CN": [
    "hudChrome.donate.close",
    "hudChrome.donate.copied",
    "hudChrome.donate.copy",
    "hudChrome.donate.intro",
    "hudChrome.donate.pixLabel",
    "hudChrome.donate.qrAlt",
    "hudChrome.donate.thanks",
    "hudChrome.donate.title"
  ],
  "zh_TW": [
    "hudChrome.donate.close",
    "hudChrome.donate.copied",
    "hudChrome.donate.copy",
    "hudChrome.donate.intro",
    "hudChrome.donate.pixLabel",
    "hudChrome.donate.qrAlt",
    "hudChrome.donate.thanks",
    "hudChrome.donate.title"
  ],
  "ko_KR": [
    "hudChrome.donate.close",
    "hudChrome.donate.copied",
    "hudChrome.donate.copy",
    "hudChrome.donate.intro",
    "hudChrome.donate.pixLabel",
    "hudChrome.donate.qrAlt",
    "hudChrome.donate.thanks",
    "hudChrome.donate.title"
  ],
  "ja_JP": [
    "hudChrome.donate.close",
    "hudChrome.donate.copied",
    "hudChrome.donate.copy",
    "hudChrome.donate.intro",
    "hudChrome.donate.pixLabel",
    "hudChrome.donate.qrAlt",
    "hudChrome.donate.thanks",
    "hudChrome.donate.title"
  ],
  "pt_BR": [
    "hudChrome.donate.close",
    "hudChrome.donate.copied",
    "hudChrome.donate.copy",
    "hudChrome.donate.intro",
    "hudChrome.donate.pixLabel",
    "hudChrome.donate.qrAlt",
    "hudChrome.donate.thanks",
    "hudChrome.donate.title"
  ],
  "ru_RU": [
    "hudChrome.donate.close",
    "hudChrome.donate.copied",
    "hudChrome.donate.copy",
    "hudChrome.donate.intro",
    "hudChrome.donate.pixLabel",
    "hudChrome.donate.qrAlt",
    "hudChrome.donate.thanks",
    "hudChrome.donate.title"
  ]
};
