import type {
  CampDef,
  GroundObjectDef,
  ItemDef,
  MobTemplate,
  NpcDef,
  QuestDef,
  ZoneDef,
  ZonePropsDef,
} from '../types';

// Zone 4 - The Ashen Wastes: a dead, blighted land north of Thornpeak Heights,
// reached through a mountain pass. Grey/brown/dead palette via the 'blight' biome,
// with the Naxx necropolis (the Claudexxaramas) drifting LOW over the ground.
//
// LORE - The Coming of the Claudexxaramas:
//   For ages the skies over Tupanor were calm. Then came the Claudexxaramas, a
//   drifting necropolis that anchored above the northern wastes and bled corruption
//   into the land below. Where its shadow falls the ground turns to ash, the dead do
//   not rest, and the living sicken. The DAWN OF CLAUDE is the order that rose against
//   the blight: knights, clerics, and scholars who hold the line at Gravewatch, mean to
//   cleanse the Ashen Wastes, and one day breach the floating horror to end the plague
//   at its source. Stand with the Dawn, earn their trust, and they will arm you for the
//   assault on Naxxramas itself.
//
// All overworld content here grants Dawn of Claude reputation: quests on turn-in
// (repReward) and the blighted dead on death (repOnKill, Argent-Dawn style).

export const ZONE4_ZONE: ZoneDef = {
  id: 'ashen_wastes',
  name: 'The Ashen Wastes',
  zMin: 900, // must equal Thornpeak's zMax (zone bands tile contiguously)
  zMax: 1260,
  levelRange: [20, 20],
  biome: 'blight',
  hub: { x: 0, z: 1020, radius: 20, name: 'Gravewatch' },
  graveyard: { x: 15, z: 1005 },
  lakes: [{ x: -60, z: 1100, radius: 16 }],
  pois: [
    { x: 0, z: 1020, label: 'Gravewatch' },
    { x: 0, z: 905, label: 'The Ashen Pass' },
    { x: -70, z: 1100, label: 'The Stillmere' },
    { x: 80, z: 1075, label: 'The Bonefields' },
    { x: -55, z: 1170, label: 'Hollow Barrows' },
    { x: 45, z: 1215, label: 'The Pale Reach' },
  ],
  welcome: 'The Ashen Wastes stretch out, grey and lifeless. Something vast drifts low over the dead ground.',
};

export const ZONE4_ROADS: { x: number; z: number }[][] = [
  // the dead road climbing north out of the pass up to Gravewatch
  [{ x: 0, z: 898 }, { x: 0, z: 1020 }],
];

// ---------------------------------------------------------------------------
// Mobs - the blighted dead under the Claudexxaramas. All level 20 (the cap);
// the danger gradient is carried by elite/rare/boss tiers and HP/armor, not by
// level, since players cap at 20. Every kill grants Dawn of Claude reputation.
// ---------------------------------------------------------------------------

export const ZONE4_MOBS: Record<string, MobTemplate> = {
  blighted_husk: {
    id: 'blighted_husk',
    name: 'Blighted Husk',
    minLevel: 20,
    maxLevel: 20,
    family: 'undead',
    hpBase: 70,
    hpPerLevel: 24,
    dmgBase: 12,
    dmgPerLevel: 2.7,
    attackSpeed: 2.4,
    armorPerLevel: 18,
    moveSpeed: 6,
    aggroRadius: 10,
    // Necrotic Touch: the husk's rotten grasp festers, a nature-school plague DoT.
    bleed: { chance: 0.25, perTick: 6, interval: 3, duration: 12, name: 'Necrotic Touch', school: 'nature' },
    loot: [
      { copper: 110, chance: 1 },
      { itemId: 'blight_sample', chance: 0.5, questId: 'q_aw_samples' },
    ],
    repOnKill: { faction: 'dawn_of_claude', amount: 12 },
    scale: 1.0,
    color: 0x6b6f5c,
  },
  ashen_ghoul: {
    id: 'ashen_ghoul',
    name: 'Ashen Ghoul',
    minLevel: 20,
    maxLevel: 20,
    family: 'undead',
    hpBase: 66,
    hpPerLevel: 23,
    dmgBase: 13,
    dmgPerLevel: 2.8,
    attackSpeed: 1.9,
    armorPerLevel: 16,
    moveSpeed: 8,
    aggroRadius: 11,
    // Frenzied Rend: a feral, fast-hitting clawer that goes rabid when wounded.
    enrage: { belowHpPct: 0.35, dmgMult: 1.35, hasteMult: 1.25 },
    loot: [
      { copper: 115, chance: 1 },
      { itemId: 'blight_sample', chance: 0.45, questId: 'q_aw_samples' },
    ],
    repOnKill: { faction: 'dawn_of_claude', amount: 12 },
    scale: 1.0,
    color: 0x7d8268,
  },
  plague_crawler: {
    id: 'plague_crawler',
    name: 'Plague Crawler',
    minLevel: 20,
    maxLevel: 20,
    family: 'beast',
    hpBase: 64,
    hpPerLevel: 22,
    dmgBase: 12,
    dmgPerLevel: 2.7,
    attackSpeed: 1.8,
    armorPerLevel: 16,
    moveSpeed: 8.5,
    aggroRadius: 11,
    // Diseased Bite: a corrupted vermin whose bite spreads a lingering sickness.
    bleed: { chance: 0.3, perTick: 7, interval: 3, duration: 12, name: 'Diseased Bite', school: 'nature' },
    loot: [
      { copper: 120, chance: 1 },
      { itemId: 'blight_sample', chance: 0.5, questId: 'q_aw_samples' },
    ],
    repOnKill: { faction: 'dawn_of_claude', amount: 13 },
    scale: 0.9,
    color: 0x8a7b4a,
  },
  corrupted_acolyte: {
    id: 'corrupted_acolyte',
    name: 'Corrupted Acolyte',
    minLevel: 20,
    maxLevel: 20,
    family: 'humanoid',
    hpBase: 62,
    hpPerLevel: 22,
    dmgBase: 13,
    dmgPerLevel: 2.9,
    attackSpeed: 2.0,
    armorPerLevel: 16,
    moveSpeed: 7,
    aggroRadius: 12,
    // The acolytes chant to the drifting ship; their whispers sap a caster's mind.
    enfeeble: { chance: 0.3, int: 14, duration: 12, name: 'Hollow Whisper', school: 'shadow' },
    manaBurn: { chance: 0.25, amount: 100, name: 'Mind Leech', school: 'shadow' },
    loot: [
      { copper: 130, chance: 1 },
      { itemId: 'cult_orders', chance: 0.5, questId: 'q_aw_orders' },
    ],
    repOnKill: { faction: 'dawn_of_claude', amount: 15 },
    scale: 1.0,
    color: 0x5d6b7a,
  },
  bone_reaver: {
    id: 'bone_reaver',
    name: 'Bone Reaver',
    minLevel: 20,
    maxLevel: 20,
    family: 'undead',
    hpBase: 74,
    hpPerLevel: 25,
    dmgBase: 14,
    dmgPerLevel: 3.0,
    attackSpeed: 2.3,
    armorPerLevel: 22,
    moveSpeed: 7,
    aggroRadius: 11,
    cleave: { radius: 6, mult: 0.7, name: 'Bone Cleave' },
    loot: [{ copper: 135, chance: 1 }],
    repOnKill: { faction: 'dawn_of_claude', amount: 15 },
    scale: 1.05,
    color: 0xcac3b0,
  },
  wraithling: {
    id: 'wraithling',
    name: 'Barrow Wraithling',
    minLevel: 20,
    maxLevel: 20,
    family: 'undead',
    hpBase: 68,
    hpPerLevel: 24,
    dmgBase: 14,
    dmgPerLevel: 3.1,
    attackSpeed: 2.1,
    armorPerLevel: 16,
    moveSpeed: 7.5,
    aggroRadius: 12,
    // Soul Chill: a spectral touch that withers Stamina and saps the warmth of life.
    enervate: { chance: 0.3, sta: 16, duration: 12, name: 'Soul Chill', school: 'shadow' },
    loot: [
      { copper: 145, chance: 1 },
      { itemId: 'desecrated_relic', chance: 0.55, questId: 'q_aw_relics' },
    ],
    repOnKill: { faction: 'dawn_of_claude', amount: 16 },
    scale: 1.0,
    color: 0x9fb6c4,
  },
  plaguebringer_zealot: {
    id: 'plaguebringer_zealot',
    name: 'Plaguebringer Zealot',
    minLevel: 20,
    maxLevel: 20,
    family: 'humanoid',
    elite: true,
    hpBase: 150,
    hpPerLevel: 30,
    dmgBase: 16,
    dmgPerLevel: 3.4,
    attackSpeed: 2.2,
    armorPerLevel: 24,
    moveSpeed: 7,
    aggroRadius: 13,
    aoePulse: { min: 26, max: 38, radius: 9, every: 9, name: 'Plague Burst', school: 'nature', fx: 'nova' },
    mendAlly: { healMin: 40, healMax: 60, radius: 14, every: 8, name: 'Dark Mending', school: 'shadow' },
    loot: [
      { copper: 180, chance: 1 },
      { itemId: 'ritual_focus', chance: 0.5, questId: 'q_aw_ritual' },
    ],
    repOnKill: { faction: 'dawn_of_claude', amount: 18 },
    scale: 1.1,
    color: 0x6a8a4f,
  },
  rotting_behemoth: {
    // The q_aw_behemoth target: a mountain of stitched, rotting dead lumbering off
    // the Stillmere toward Gravewatch. A small-group elite (suggestedPlayers 2).
    id: 'rotting_behemoth',
    name: 'Rotting Behemoth',
    minLevel: 20,
    maxLevel: 20,
    family: 'undead',
    elite: true,
    canSwim: true,
    ccImmune: true,
    respawnMult: 16,
    hpBase: 600,
    hpPerLevel: 90,
    dmgBase: 22,
    dmgPerLevel: 4.2,
    attackSpeed: 2.8,
    armorPerLevel: 36,
    moveSpeed: 6,
    aggroRadius: 13,
    aoePulse: { min: 30, max: 44, radius: 11, every: 10, name: 'Putrid Slam', school: 'nature', fx: 'nova' },
    knockback: { chance: 0.3, distance: 6, name: 'Sweeping Heave' },
    enrage: { belowHpPct: 0.3, dmgMult: 1.4, hasteMult: 1.25 },
    loot: [{ copper: 400, chance: 1 }],
    repOnKill: { faction: 'dawn_of_claude', amount: 35 },
    scale: 1.6,
    color: 0x6f7a55,
  },
  naxx_deathguard: {
    id: 'naxx_deathguard',
    name: 'Naxxramas Deathguard',
    minLevel: 20,
    maxLevel: 20,
    family: 'undead',
    elite: true,
    hpBase: 165,
    hpPerLevel: 32,
    dmgBase: 18,
    dmgPerLevel: 3.7,
    attackSpeed: 2.4,
    armorPerLevel: 30,
    moveSpeed: 7,
    aggroRadius: 13,
    cleave: { radius: 7, mult: 0.75, name: 'Deathguard Sweep' },
    // Cleaving wounds from the ship's wardens are slow to close.
    mortalStrike: { chance: 0.35, healReduction: 0.5, duration: 10, name: 'Necrotic Wound', school: 'shadow' },
    loot: [
      { copper: 200, chance: 1 },
      { itemId: 'ship_fragment', chance: 0.4 },
    ],
    repOnKill: { faction: 'dawn_of_claude', amount: 22 },
    scale: 1.15,
    color: 0x8b94a0,
  },
  morthax_the_hollow: {
    // Rare elite: a hollowed champion the ship raised from a fallen Dawn knight,
    // prowling the Hollow Barrows. A bounty target (q_aw_morthax).
    id: 'morthax_the_hollow',
    name: 'Morthax the Hollow',
    minLevel: 20,
    maxLevel: 20,
    family: 'undead',
    rare: true,
    elite: true,
    canSwim: true,
    ccImmune: true,
    respawnMult: 864,
    hpBase: 520,
    hpPerLevel: 80,
    dmgBase: 24,
    dmgPerLevel: 4.6,
    attackSpeed: 2.3,
    armorPerLevel: 40,
    moveSpeed: 7.2,
    aggroRadius: 14,
    aoePulse: { min: 30, max: 44, radius: 10, every: 10, name: 'Hollow Nova', school: 'shadow', fx: 'nova' },
    enrage: { belowHpPct: 0.3, dmgMult: 1.45, hasteMult: 1.3 },
    loot: [
      { copper: 700, chance: 1 },
      { itemId: 'hollow_heart', chance: 1, questId: 'q_aw_morthax' },
    ],
    repOnKill: { faction: 'dawn_of_claude', amount: 60 },
    scale: 1.3,
    color: 0xb8c0c8,
  },
  gravelord_oss: {
    // Zone boss: the Claudexxaramas' lieutenant on the ground, anchoring the blight
    // at the Pale Reach. The capstone group target (q_aw_gravelord).
    id: 'gravelord_oss',
    name: 'Gravelord Oss',
    minLevel: 20,
    maxLevel: 20,
    family: 'undead',
    elite: true,
    boss: true,
    canSwim: true,
    ccImmune: true,
    respawnMult: 1000,
    hpBase: 360,
    hpPerLevel: 56,
    dmgBase: 19,
    dmgPerLevel: 3.9,
    attackSpeed: 2.4,
    armorPerLevel: 44,
    moveSpeed: 6.8,
    aggroRadius: 16,
    aoePulse: { min: 32, max: 48, radius: 11, every: 9, name: 'Grave Tide', school: 'shadow', fx: 'nova' },
    summonAdds: { mobId: 'bone_reaver', count: 2, atHpPct: [0.66, 0.33] },
    enrage: { belowHpPct: 0.25, dmgMult: 1.5, hasteMult: 1.3 },
    loot: [
      { copper: 1500, chance: 1 },
      { itemId: 'gravelord_pauldrons', chance: 0.34, rollGroup: 'gravelord_oss_chase' },
      { itemId: 'gravelord_amice', chance: 0.33, rollGroup: 'gravelord_oss_chase' },
      { itemId: 'gravelord_spaulders', chance: 0.33, rollGroup: 'gravelord_oss_chase' },
    ],
    repOnKill: { faction: 'dawn_of_claude', amount: 120 },
    scale: 1.4,
    color: 0x7a8088,
  },
};

// ---------------------------------------------------------------------------
// NPCs - the Dawn of Claude garrison at Gravewatch
// ---------------------------------------------------------------------------

export const ZONE4_NPCS: Record<string, NpcDef> = {
  dawn_commander_sera: {
    id: 'dawn_commander_sera',
    name: 'Commander Sera',
    title: 'Dawn of Claude',
    pos: { x: 3, z: 1024 },
    facing: -2.0,
    color: 0xd9b35a,
    questIds: [
      'q_aw_arrival',
      'q_aw_husks',
      'q_aw_ghouls',
      'q_aw_acolytes',
      'q_aw_behemoth',
      'q_aw_deathguard',
      'q_aw_gravelord',
    ],
    greeting:
      'Hold the line, $C. That floating tomb, the Claudexxaramas, has bled this whole land grey. The Dawn of Claude will take it back, soul by soul.',
  },
  dawn_chaplain_orin: {
    id: 'dawn_chaplain_orin',
    name: 'Chaplain Orin',
    title: 'Dawn of Claude',
    pos: { x: -9, z: 1018 },
    facing: 0.7,
    color: 0xf2efe0,
    questIds: ['q_aw_crawlers', 'q_aw_samples', 'q_aw_wraiths', 'q_aw_relics'],
    greeting:
      'The Light still reaches here, $N, though it is thin. Help me tend the dying and break the plague the ship pours down on us.',
  },
  dawn_quartermaster_henning: {
    id: 'dawn_quartermaster_henning',
    name: 'Quartermaster Henning',
    title: 'Dawn of Claude',
    pos: { x: -4, z: 1028 },
    facing: 1.6,
    color: 0xca8a2a,
    questIds: ['q_aw_reavers', 'q_aw_hold', 'q_aw_morthax'],
    // The reputation vendor. Each tier-0.5 piece is gated by standing (vendorReqs):
    // the full set demands Exalted, the mainhand being the final Exalted unlock.
    vendorItems: [
      'healing_potion',
      'mana_potion',
      // Dawnguard Battlegear (plate - warrior/paladin/shaman)
      'dawnguard_sabatons',
      'dawnguard_gauntlets',
      'dawnguard_girdle',
      'dawnguard_greathelm',
      'dawnguard_legplates',
      'dawnguard_pauldrons',
      'dawnguard_breastplate',
      'dawnguard_blade',
      // Vestments of the Dawn (cloth - mage/priest/warlock/druid)
      'dawn_slippers',
      'dawn_handwraps',
      'dawn_cord',
      'dawn_cowl',
      'dawn_leggings',
      'dawn_mantle',
      'dawn_robe',
      'dawn_scepter',
      // Dawnstalker Armor (leather - rogue/hunter)
      'dawnstalker_treads',
      'dawnstalker_grips',
      'dawnstalker_belt',
      'dawnstalker_mask',
      'dawnstalker_legguards',
      'dawnstalker_spaulders',
      'dawnstalker_tunic',
      'dawnstalker_dagger',
    ],
    vendorReqs: {
      // Friendly: the boots, gloves, and belt of each set
      dawnguard_sabatons: { faction: 'dawn_of_claude', standing: 'friendly' },
      dawnguard_gauntlets: { faction: 'dawn_of_claude', standing: 'friendly' },
      dawnguard_girdle: { faction: 'dawn_of_claude', standing: 'friendly' },
      dawn_slippers: { faction: 'dawn_of_claude', standing: 'friendly' },
      dawn_handwraps: { faction: 'dawn_of_claude', standing: 'friendly' },
      dawn_cord: { faction: 'dawn_of_claude', standing: 'friendly' },
      dawnstalker_treads: { faction: 'dawn_of_claude', standing: 'friendly' },
      dawnstalker_grips: { faction: 'dawn_of_claude', standing: 'friendly' },
      dawnstalker_belt: { faction: 'dawn_of_claude', standing: 'friendly' },
      // Honored: the helm and legs
      dawnguard_greathelm: { faction: 'dawn_of_claude', standing: 'honored' },
      dawnguard_legplates: { faction: 'dawn_of_claude', standing: 'honored' },
      dawn_cowl: { faction: 'dawn_of_claude', standing: 'honored' },
      dawn_leggings: { faction: 'dawn_of_claude', standing: 'honored' },
      dawnstalker_mask: { faction: 'dawn_of_claude', standing: 'honored' },
      dawnstalker_legguards: { faction: 'dawn_of_claude', standing: 'honored' },
      // Revered: the shoulders and chest
      dawnguard_pauldrons: { faction: 'dawn_of_claude', standing: 'revered' },
      dawnguard_breastplate: { faction: 'dawn_of_claude', standing: 'revered' },
      dawn_mantle: { faction: 'dawn_of_claude', standing: 'revered' },
      dawn_robe: { faction: 'dawn_of_claude', standing: 'revered' },
      dawnstalker_spaulders: { faction: 'dawn_of_claude', standing: 'revered' },
      dawnstalker_tunic: { faction: 'dawn_of_claude', standing: 'revered' },
      // Exalted: the weapon completes the set
      dawnguard_blade: { faction: 'dawn_of_claude', standing: 'exalted' },
      dawn_scepter: { faction: 'dawn_of_claude', standing: 'exalted' },
      dawnstalker_dagger: { faction: 'dawn_of_claude', standing: 'exalted' },
    },
    greeting:
      'Steel and faith, $N, that is all I have to give. Earn the Dawn\'s trust and the quartermaster\'s store opens to you, piece by piece.',
  },
  dawn_scout_irelle: {
    id: 'dawn_scout_irelle',
    name: 'Scout Irelle',
    title: 'Dawn of Claude',
    pos: { x: 8, z: 1030 },
    facing: -2.4,
    color: 0x6e8b3d,
    questIds: ['q_aw_orders', 'q_aw_zealots', 'q_aw_pale_reach'],
    greeting:
      'I have mapped the dead roads as far north as I dare, $C. The closer to the Pale Reach, the louder the ship whispers. Watch your step.',
  },
  dawn_archivist_vael: {
    id: 'dawn_archivist_vael',
    name: 'Archivist Vael',
    title: 'Dawn of Claude',
    pos: { x: 12, z: 1016 },
    facing: -1.2,
    color: 0x3b6ea5,
    questIds: ['q_aw_ritual', 'q_aw_attune_1', 'q_aw_attunement'],
    greeting:
      'Every shard of that necropolis I can study is a crack we might one day pry open, $N. Bring me what the dead carry, and we will plan the breach together.',
  },
};

// ---------------------------------------------------------------------------
// Quests - 20, all granting Dawn of Claude reputation (repReward). Combined with
// repOnKill grinding, a dedicated player can climb from Neutral to Exalted and
// buy the full tier-0.5 set the quartermaster gates behind standing.
// ---------------------------------------------------------------------------

export const ZONE4_QUESTS: Record<string, QuestDef> = {
  q_aw_arrival: {
    id: 'q_aw_arrival',
    name: 'Ashes and Omens',
    giverNpcId: 'dawn_commander_sera',
    turnInNpcId: 'dawn_commander_sera',
    text: "Welcome to Gravewatch, $N - what little of it the blight has left us. The husks of the fallen claw at our walls every night. Put eight of them down so my soldiers can sleep, and the Dawn of Claude will count you a friend in the making.",
    completionText: "Eight fewer horrors at the gate. You have a steady hand, $N. The Dawn remembers those who stand with us.",
    objectives: [{ type: 'kill', targetMobId: 'blighted_husk', count: 8, label: 'Blighted Husk slain' }],
    xpReward: 4500,
    copperReward: 1500,
    itemRewards: {},
    repReward: { faction: 'dawn_of_claude', amount: 250 },
    minLevel: 20,
  },
  q_aw_husks: {
    id: 'q_aw_husks',
    name: 'The Walking Blight',
    giverNpcId: 'dawn_commander_sera',
    turnInNpcId: 'dawn_commander_sera',
    text: 'The husks are not mindless, $N - they gather, they probe our lines. Cull twelve more before they learn where we are weakest. Take these treads for the walking; the wastes are hard on boots.',
    completionText: 'Good. Every husk you burn is one that cannot rise again tonight.',
    objectives: [{ type: 'kill', targetMobId: 'blighted_husk', count: 12, label: 'Blighted Husk slain' }],
    xpReward: 4800,
    copperReward: 1800,
    itemRewards: { warrior: 'ashen_warboots', mage: 'ashen_slippers', rogue: 'ashen_treads' },
    repReward: { faction: 'dawn_of_claude', amount: 350 },
    requiresQuest: 'q_aw_arrival',
  },
  q_aw_ghouls: {
    id: 'q_aw_ghouls',
    name: 'Feral Hunger',
    giverNpcId: 'dawn_commander_sera',
    turnInNpcId: 'dawn_commander_sera',
    text: 'The ashen ghouls hunt in packs out on the Bonefields, fast and rabid. They have dragged off two of my scouts already. Thin them - ten should break the pack - before they grow bold enough to rush the gate.',
    completionText: 'The packs are scattered. My scouts can range the Bonefields again, thanks to you.',
    objectives: [{ type: 'kill', targetMobId: 'ashen_ghoul', count: 10, label: 'Ashen Ghoul slain' }],
    xpReward: 4800,
    copperReward: 1800,
    itemRewards: {},
    repReward: { faction: 'dawn_of_claude', amount: 350 },
  },
  q_aw_crawlers: {
    id: 'q_aw_crawlers',
    name: 'Spreading Sickness',
    giverNpcId: 'dawn_chaplain_orin',
    turnInNpcId: 'dawn_chaplain_orin',
    text: 'The plague crawlers carry the blight in their bite, $N, and they breed in the Stillmere mud. Kill ten of them. Where they walk, the sickness follows, and I have too many cots filled already.',
    completionText: 'The wards on the cots will hold a little longer now. The Light thanks you, even when I forget to.',
    objectives: [{ type: 'kill', targetMobId: 'plague_crawler', count: 10, label: 'Plague Crawler slain' }],
    xpReward: 4800,
    copperReward: 1800,
    itemRewards: {},
    repReward: { faction: 'dawn_of_claude', amount: 350 },
  },
  q_aw_samples: {
    id: 'q_aw_samples',
    name: 'Tainted Samples',
    giverNpcId: 'dawn_chaplain_orin',
    turnInNpcId: 'dawn_chaplain_orin',
    text: 'To cure the blight I must first understand it. The husks and crawlers are soaked through with it - bring me six tainted samples of their corrupted flesh, and handle them carefully. The taint does not care whose blood it spoils.',
    completionText: 'Six samples, each worse than the last. The corruption is... patterned. Deliberate. This is no natural plague, $N.',
    objectives: [{ type: 'collect', itemId: 'blight_sample', count: 6, label: 'Tainted Sample' }],
    xpReward: 4600,
    copperReward: 1700,
    itemRewards: {},
    repReward: { faction: 'dawn_of_claude', amount: 300 },
    requiresQuest: 'q_aw_crawlers',
  },
  q_aw_acolytes: {
    id: 'q_aw_acolytes',
    name: 'Voices of the Ship',
    giverNpcId: 'dawn_commander_sera',
    turnInNpcId: 'dawn_commander_sera',
    text: 'Living men kneel to the Claudexxaramas now, $N - corrupted acolytes who chant its will across the wastes. They are no longer ours to save. Silence ten of them. Take these handguards; you will earn worse before this is done.',
    completionText: 'The chanting falters. Whatever the ship is building, you have cost it ten willing throats.',
    objectives: [{ type: 'kill', targetMobId: 'corrupted_acolyte', count: 10, label: 'Corrupted Acolyte slain' }],
    xpReward: 5000,
    copperReward: 2000,
    itemRewards: { warrior: 'dawnward_gauntlets', mage: 'dawnward_gloves', rogue: 'dawnward_grips' },
    repReward: { faction: 'dawn_of_claude', amount: 400 },
    minLevel: 20,
  },
  q_aw_orders: {
    id: 'q_aw_orders',
    name: 'Orders from Above',
    giverNpcId: 'dawn_scout_irelle',
    turnInNpcId: 'dawn_scout_irelle',
    text: 'The acolytes carry written orders, $N - the ship speaks and they transcribe. Cut down eight more and bring me four sets of those orders. I would know what the Claudexxaramas commands before it is commanded of us.',
    completionText: 'This script crawls when you look at it. But it is orders, true enough: gather the dead, ready the Pale Reach. They are preparing for something.',
    objectives: [
      { type: 'kill', targetMobId: 'corrupted_acolyte', count: 8, label: 'Corrupted Acolyte slain' },
      { type: 'collect', itemId: 'cult_orders', count: 4, label: 'Corrupted Orders' },
    ],
    xpReward: 5200,
    copperReward: 2100,
    itemRewards: {},
    repReward: { faction: 'dawn_of_claude', amount: 450 },
    requiresQuest: 'q_aw_acolytes',
  },
  q_aw_reavers: {
    id: 'q_aw_reavers',
    name: 'Bonefields',
    giverNpcId: 'dawn_quartermaster_henning',
    turnInNpcId: 'dawn_quartermaster_henning',
    text: 'The bone reavers are walking armories, $N - old soldiers reforged into the ship\'s blades. Break twelve of them on the Bonefields. Every reaver you scatter is steel that will never swing at the Dawn again.',
    completionText: 'Twelve reavers down to splinters. Salvage like that keeps my forge lit. Well done.',
    objectives: [{ type: 'kill', targetMobId: 'bone_reaver', count: 12, label: 'Bone Reaver slain' }],
    xpReward: 5200,
    copperReward: 2100,
    itemRewards: {},
    repReward: { faction: 'dawn_of_claude', amount: 450 },
  },
  q_aw_wraiths: {
    id: 'q_aw_wraiths',
    name: 'Hollow Barrows',
    giverNpcId: 'dawn_chaplain_orin',
    turnInNpcId: 'dawn_chaplain_orin',
    text: 'The old barrows north of here have woken, $N. Wraithlings drift from the graves, cold things that drink the warmth out of the living. Put ten of them to rest. The dead of these wastes deserve better than to serve that ship.',
    completionText: 'Ten souls eased back into the dark. I prayed over each as you described it. It is a small mercy, but it is ours.',
    objectives: [{ type: 'kill', targetMobId: 'wraithling', count: 10, label: 'Barrow Wraithling slain' }],
    xpReward: 5200,
    copperReward: 2100,
    itemRewards: {},
    repReward: { faction: 'dawn_of_claude', amount: 450 },
    minLevel: 20,
  },
  q_aw_relics: {
    id: 'q_aw_relics',
    name: 'Sanctified Relics',
    giverNpcId: 'dawn_chaplain_orin',
    turnInNpcId: 'dawn_chaplain_orin',
    text: 'The barrows hold relics of the old faith - sanctified once, desecrated now by the wraithlings\' touch. Recover five from the graves, $N. Cleansed and re-blessed, they will ward the cots far better than my failing prayers.',
    completionText: 'Five relics, and each one warms in my hands as the taint lifts. The Light is not gone from this place. It only needed carrying home.',
    objectives: [{ type: 'collect', itemId: 'desecrated_relic', count: 5, label: 'Desecrated Relic' }],
    xpReward: 5000,
    copperReward: 2000,
    itemRewards: {},
    repReward: { faction: 'dawn_of_claude', amount: 400 },
    requiresQuest: 'q_aw_wraiths',
  },
  q_aw_hold: {
    id: 'q_aw_hold',
    name: 'Holding Gravewatch',
    giverNpcId: 'dawn_quartermaster_henning',
    turnInNpcId: 'dawn_quartermaster_henning',
    text: 'Plain truth, $N: we are losing ground. The reavers press the Bonefields harder each night. I need fourteen more of them broken to buy the garrison a week of breathing room. Can the Dawn count on you?',
    completionText: 'A week. You have bought us a week. I will not waste it - and I will not forget who earned it.',
    objectives: [{ type: 'kill', targetMobId: 'bone_reaver', count: 14, label: 'Bone Reaver slain' }],
    xpReward: 5000,
    copperReward: 2000,
    itemRewards: {},
    repReward: { faction: 'dawn_of_claude', amount: 350 },
    requiresQuest: 'q_aw_reavers',
  },
  q_aw_behemoth: {
    id: 'q_aw_behemoth',
    name: 'The Rotting Behemoth',
    giverNpcId: 'dawn_commander_sera',
    turnInNpcId: 'dawn_commander_sera',
    text: 'Something huge moves on the Stillmere, $N - a behemoth of stitched and rotting dead, big enough to walk through our wall like a fence. Take a companion or two and put it down before it reaches Gravewatch. This girdle should help you bear the blows.',
    completionText: 'You felled the mountain of meat. I felt the ground stop shaking from up here. The Dawn owes you for that one.',
    objectives: [{ type: 'kill', targetMobId: 'rotting_behemoth', count: 1, label: 'Rotting Behemoth slain' }],
    xpReward: 6000,
    copperReward: 3000,
    itemRewards: { warrior: 'behemoth_girdle', mage: 'behemoth_sash', rogue: 'behemoth_belt' },
    repReward: { faction: 'dawn_of_claude', amount: 600 },
    requiresQuest: 'q_aw_arrival',
    minLevel: 20,
    suggestedPlayers: 2,
  },
  q_aw_zealots: {
    id: 'q_aw_zealots',
    name: 'Plaguebringers',
    giverNpcId: 'dawn_scout_irelle',
    turnInNpcId: 'dawn_scout_irelle',
    text: 'The plaguebringer zealots seed the Pale Reach approach with their bursts of rot, $N, and they mend each other faster than a lone blade can drop them. Kill eight. Hit them hard, hit them together, and do not let them circle to heal.',
    completionText: 'Eight zealots, and the rot they were sowing dies with them. The approach is passable again - barely.',
    objectives: [{ type: 'kill', targetMobId: 'plaguebringer_zealot', count: 8, label: 'Plaguebringer Zealot slain' }],
    xpReward: 5500,
    copperReward: 2400,
    itemRewards: {},
    repReward: { faction: 'dawn_of_claude', amount: 500 },
    minLevel: 20,
  },
  q_aw_deathguard: {
    id: 'q_aw_deathguard',
    name: "The Ship's Wardens",
    giverNpcId: 'dawn_commander_sera',
    turnInNpcId: 'dawn_commander_sera',
    text: 'The Naxxramas deathguards are the ship\'s own wardens, $N - elite dead in black plate, posted where the Claudexxaramas hangs lowest. Break ten of them. I need to know if the Dawn can fight in the necropolis\'s very shadow. This helm was a deathguard\'s once; wear it against them.',
    completionText: 'Ten wardens down, in the ship\'s own shadow. Then it can be done. Then we can take the fight UP, one day. You have shown me that, $N.',
    objectives: [{ type: 'kill', targetMobId: 'naxx_deathguard', count: 10, label: 'Naxxramas Deathguard slain' }],
    xpReward: 6000,
    copperReward: 3000,
    itemRewards: { warrior: 'deathward_helm', mage: 'deathward_hood', rogue: 'deathward_cowl' },
    repReward: { faction: 'dawn_of_claude', amount: 600 },
    minLevel: 20,
  },
  q_aw_morthax: {
    id: 'q_aw_morthax',
    name: 'The Hollow Lord',
    giverNpcId: 'dawn_quartermaster_henning',
    turnInNpcId: 'dawn_quartermaster_henning',
    text: 'One of ours fell in the Hollow Barrows last season - a knight named Morthax. The ship raised him, $N, and now Morthax the Hollow hunts the men he once led. Find him. End him. Bring me his heart so I know the thing wearing his face is truly gone.',
    completionText: 'Cold. The heart is stone-cold and hollow as the name they gave him. Rest now, Morthax. You served the Dawn to the last, and past it.',
    objectives: [{ type: 'collect', itemId: 'hollow_heart', count: 1, label: 'Hollow Heart' }],
    xpReward: 6500,
    copperReward: 3500,
    itemRewards: {},
    repReward: { faction: 'dawn_of_claude', amount: 700 },
    minLevel: 20,
  },
  q_aw_pale_reach: {
    id: 'q_aw_pale_reach',
    name: 'Into the Pale Reach',
    giverNpcId: 'dawn_scout_irelle',
    turnInNpcId: 'dawn_scout_irelle',
    text: 'The Pale Reach is the worst of it, $N - bare ground directly beneath the anchored ship, thick with deathguards. I cannot map it alone. Carve me a path: drop eight Naxxramas deathguards while I sketch the ground behind you.',
    completionText: 'I have it - the whole Reach, mapped at last, every patrol and pylon. Archivist Vael will want this. So will the Commander, when the day comes to march on the ship.',
    objectives: [{ type: 'kill', targetMobId: 'naxx_deathguard', count: 8, label: 'Naxxramas Deathguard slain' }],
    xpReward: 5500,
    copperReward: 2400,
    itemRewards: {},
    repReward: { faction: 'dawn_of_claude', amount: 400 },
    requiresQuest: 'q_aw_deathguard',
  },
  q_aw_ritual: {
    id: 'q_aw_ritual',
    name: 'Break the Ritual',
    giverNpcId: 'dawn_archivist_vael',
    turnInNpcId: 'dawn_archivist_vael',
    text: 'The zealots are working a ritual on the Pale Reach to draw the Claudexxaramas lower still, $N. Each carries a ritual focus that anchors the rite. Take four of them, and kill six zealots in the doing - sever the anchors and the ritual stalls.',
    completionText: 'The foci go dark the moment they leave the Reach. Four anchors cut. The ship hangs no lower today, and that is a victory, however small.',
    objectives: [
      { type: 'collect', itemId: 'ritual_focus', count: 4, label: 'Ritual Focus' },
      { type: 'kill', targetMobId: 'plaguebringer_zealot', count: 6, label: 'Plaguebringer Zealot slain' },
    ],
    xpReward: 6000,
    copperReward: 3000,
    itemRewards: {},
    repReward: { faction: 'dawn_of_claude', amount: 600 },
    minLevel: 20,
  },
  q_aw_attune_1: {
    id: 'q_aw_attune_1',
    name: 'Echoes of the Claudexxaramas',
    giverNpcId: 'dawn_archivist_vael',
    turnInNpcId: 'dawn_archivist_vael',
    text: 'To breach the necropolis we must first understand it, $N. Its wardens carry fragments of its hull - dead metal that still hums with the ship\'s rhythm. Bring me three ship fragments off the deathguards, and I will start to learn the song of Naxxramas.',
    completionText: 'They resonate together - listen. Three notes of the same dirge. Given enough of these, Archivist, I could map the way INSIDE. This is how we breach it.',
    objectives: [{ type: 'collect', itemId: 'ship_fragment', count: 3, label: 'Ship Fragment' }],
    xpReward: 6500,
    copperReward: 3500,
    itemRewards: {},
    repReward: { faction: 'dawn_of_claude', amount: 700 },
    requiresQuest: 'q_aw_ritual',
  },
  q_aw_gravelord: {
    id: 'q_aw_gravelord',
    name: 'Gravelord Oss',
    giverNpcId: 'dawn_commander_sera',
    turnInNpcId: 'dawn_commander_sera',
    text: 'Gravelord Oss is the ship\'s hand on the ground, $N - the lieutenant who anchors the whole blight to the Pale Reach. Gather your strongest companions; this is no fight for one, or even three. Cut down the Gravelord and the wastes themselves may start to heal.',
    completionText: 'Oss is dead, and look - the ash at the Reach is already paling toward grey-green. You did not just kill a lieutenant, $N. You showed the Dawn that the Claudexxaramas can bleed.',
    objectives: [{ type: 'kill', targetMobId: 'gravelord_oss', count: 1, label: 'Gravelord Oss slain' }],
    xpReward: 8000,
    copperReward: 5000,
    itemRewards: { warrior: 'gravelord_pauldrons', mage: 'gravelord_amice', rogue: 'gravelord_spaulders' },
    repReward: { faction: 'dawn_of_claude', amount: 1000 },
    requiresQuest: 'q_aw_deathguard',
    minLevel: 20,
    suggestedPlayers: 3,
  },
  q_aw_attunement: {
    id: 'q_aw_attunement',
    name: 'The Breach of Naxxramas',
    giverNpcId: 'dawn_archivist_vael',
    turnInNpcId: 'dawn_archivist_vael',
    text: 'With Oss dead and the Gravelord\'s anchor broken, the ship hangs vulnerable, $N. This is the moment. Bring me five more ship fragments and I will forge them into a Sigil of the Dawn - your attunement to Naxxramas itself. When the Dawn of Claude finally storms that necropolis, the sigil-bearers lead the breach, and the assault will cost us half the blood and steel it should.',
    completionText: 'It is done. The Sigil of the Dawn is yours, $N - proof to every soul in this order that you are ready for the necropolis. When we march on the Claudexxaramas, you march at the front. Exalted among us, attuned to the breach. The Dawn could ask for no truer champion.',
    objectives: [{ type: 'collect', itemId: 'ship_fragment', count: 5, label: 'Ship Fragment' }],
    xpReward: 9000,
    copperReward: 6000,
    // The Naxxramas attunement, granted to every class.
    itemRewards: { warrior: 'sigil_of_the_dawn', mage: 'sigil_of_the_dawn', rogue: 'sigil_of_the_dawn' },
    repReward: { faction: 'dawn_of_claude', amount: 1500 },
    requiresQuest: 'q_aw_gravelord',
    minLevel: 20,
  },
};

export const ZONE4_QUEST_ORDER: string[] = [
  'q_aw_arrival',
  'q_aw_husks',
  'q_aw_ghouls',
  'q_aw_crawlers',
  'q_aw_samples',
  'q_aw_acolytes',
  'q_aw_orders',
  'q_aw_reavers',
  'q_aw_wraiths',
  'q_aw_relics',
  'q_aw_hold',
  'q_aw_behemoth',
  'q_aw_zealots',
  'q_aw_deathguard',
  'q_aw_morthax',
  'q_aw_pale_reach',
  'q_aw_ritual',
  'q_aw_attune_1',
  'q_aw_gravelord',
  'q_aw_attunement',
];

// ---------------------------------------------------------------------------
// Camps (APPENDED LAST in data.ts CAMPS - preserves world-gen RNG draw order).
// ---------------------------------------------------------------------------

export const ZONE4_CAMPS: CampDef[] = [
  // Blighted husks: pressing the hub and the near Bonefields
  { mobId: 'blighted_husk', center: { x: 35, z: 1055 }, radius: 20, count: 8 },
  { mobId: 'blighted_husk', center: { x: -25, z: 1060 }, radius: 18, count: 6 },
  // Ashen ghoul packs: the Bonefields
  { mobId: 'ashen_ghoul', center: { x: 80, z: 1075 }, radius: 20, count: 8 },
  { mobId: 'ashen_ghoul', center: { x: 60, z: 1095 }, radius: 16, count: 5 },
  // Plague crawlers: the Stillmere mud, west
  { mobId: 'plague_crawler', center: { x: -70, z: 1100 }, radius: 20, count: 8 },
  { mobId: 'plague_crawler', center: { x: -90, z: 1085 }, radius: 16, count: 5 },
  // Corrupted acolytes: a chanting circle between hub and barrows
  { mobId: 'corrupted_acolyte', center: { x: 10, z: 1120 }, radius: 18, count: 7 },
  { mobId: 'corrupted_acolyte', center: { x: -15, z: 1135 }, radius: 14, count: 5 },
  // Bone reavers: the deep Bonefields, east
  { mobId: 'bone_reaver', center: { x: 95, z: 1110 }, radius: 20, count: 8 },
  { mobId: 'bone_reaver', center: { x: 70, z: 1130 }, radius: 16, count: 6 },
  // Barrow wraithlings + Morthax: the Hollow Barrows
  { mobId: 'wraithling', center: { x: -55, z: 1170 }, radius: 20, count: 8 },
  { mobId: 'wraithling', center: { x: -35, z: 1185 }, radius: 16, count: 6 },
  { mobId: 'morthax_the_hollow', center: { x: -62, z: 1180 }, radius: 4, count: 1 },
  // Rotting behemoth: lumbering across the Stillmere toward the hub
  { mobId: 'rotting_behemoth', center: { x: -50, z: 1125 }, radius: 6, count: 1 },
  // Plaguebringer zealots: the Pale Reach approach
  { mobId: 'plaguebringer_zealot', center: { x: 20, z: 1190 }, radius: 18, count: 6 },
  { mobId: 'plaguebringer_zealot', center: { x: 40, z: 1200 }, radius: 14, count: 4 },
  // Naxxramas deathguards: the Pale Reach, under the ship
  { mobId: 'naxx_deathguard', center: { x: 45, z: 1215 }, radius: 20, count: 8 },
  { mobId: 'naxx_deathguard', center: { x: 25, z: 1230 }, radius: 16, count: 6 },
  // Gravelord Oss: the heart of the Pale Reach
  { mobId: 'gravelord_oss', center: { x: 48, z: 1235 }, radius: 3, count: 1 },
];

export const ZONE4_OBJECTS: GroundObjectDef[] = [
  {
    itemId: 'desecrated_relic',
    name: 'Desecrated Relic',
    positions: [
      { x: -58, z: 1162 },
      { x: -50, z: 1168 },
      { x: -44, z: 1176 },
      { x: -60, z: 1182 },
      { x: -38, z: 1190 },
      { x: -52, z: 1196 },
    ],
  },
  {
    itemId: 'ritual_focus',
    name: 'Ritual Focus',
    positions: [
      { x: 18, z: 1192 },
      { x: 28, z: 1198 },
      { x: 38, z: 1204 },
      { x: 30, z: 1212 },
      { x: 22, z: 1220 },
    ],
  },
];

// ---------------------------------------------------------------------------
// Items
// ---------------------------------------------------------------------------

const PLATE = ['warrior', 'paladin', 'shaman'] as const;
const CLOTH = ['mage', 'priest', 'warlock', 'druid'] as const;
const LEATHER = ['rogue', 'hunter'] as const;

export const ZONE4_ITEMS: Record<string, ItemDef> = {
  // --- quest items ---
  blight_sample: { id: 'blight_sample', name: 'Tainted Sample', kind: 'quest', sellValue: 0, questId: 'q_aw_samples' },
  cult_orders: { id: 'cult_orders', name: 'Corrupted Orders', kind: 'quest', sellValue: 0, questId: 'q_aw_orders' },
  desecrated_relic: { id: 'desecrated_relic', name: 'Desecrated Relic', kind: 'quest', sellValue: 0, questId: 'q_aw_relics' },
  ritual_focus: { id: 'ritual_focus', name: 'Ritual Focus', kind: 'quest', sellValue: 0, questId: 'q_aw_ritual' },
  ship_fragment: { id: 'ship_fragment', name: 'Ship Fragment', kind: 'quest', sellValue: 0, questId: 'q_aw_attune_1' },
  hollow_heart: { id: 'hollow_heart', name: 'Hollow Heart', kind: 'quest', sellValue: 0, questId: 'q_aw_morthax' },
  // The Naxxramas attunement: the capstone reward. Its presence (and the completed
  // q_aw_attunement) is the flag a future Naxx raid reads to cut its material cost.
  sigil_of_the_dawn: {
    id: 'sigil_of_the_dawn',
    name: 'Sigil of the Dawn',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_aw_attunement',
  },

  // --- quest reward gear (uncommon, archetype-keyed) ---
  ashen_warboots: { id: 'ashen_warboots', name: 'Ashen Warboots', kind: 'armor', slot: 'feet', quality: 'uncommon', stats: { armor: 120, sta: 7, str: 4 }, sellValue: 700, requiredClass: [...PLATE] },
  ashen_slippers: { id: 'ashen_slippers', name: 'Ashen Slippers', kind: 'armor', slot: 'feet', quality: 'uncommon', stats: { armor: 32, int: 7, spi: 4 }, sellValue: 700, requiredClass: [...CLOTH] },
  ashen_treads: { id: 'ashen_treads', name: 'Ashen Treads', kind: 'armor', slot: 'feet', quality: 'uncommon', stats: { armor: 72, agi: 7, sta: 3 }, sellValue: 700, requiredClass: [...LEATHER] },
  dawnward_gauntlets: { id: 'dawnward_gauntlets', name: 'Dawnward Gauntlets', kind: 'armor', slot: 'gloves', quality: 'uncommon', stats: { armor: 118, sta: 6, str: 5 }, sellValue: 750, requiredClass: [...PLATE] },
  dawnward_gloves: { id: 'dawnward_gloves', name: 'Dawnward Gloves', kind: 'armor', slot: 'gloves', quality: 'uncommon', stats: { armor: 30, int: 7, spi: 3 }, sellValue: 750, requiredClass: [...CLOTH] },
  dawnward_grips: { id: 'dawnward_grips', name: 'Dawnward Grips', kind: 'armor', slot: 'gloves', quality: 'uncommon', stats: { armor: 70, agi: 7, sta: 3 }, sellValue: 750, requiredClass: [...LEATHER] },
  behemoth_girdle: { id: 'behemoth_girdle', name: 'Behemoth Girdle', kind: 'armor', slot: 'waist', quality: 'uncommon', stats: { armor: 120, sta: 8, str: 4 }, sellValue: 900, requiredClass: [...PLATE] },
  behemoth_sash: { id: 'behemoth_sash', name: 'Behemoth Sash', kind: 'armor', slot: 'waist', quality: 'uncommon', stats: { armor: 30, int: 8, spi: 4 }, sellValue: 900, requiredClass: [...CLOTH] },
  behemoth_belt: { id: 'behemoth_belt', name: 'Behemoth Belt', kind: 'armor', slot: 'waist', quality: 'uncommon', stats: { armor: 72, agi: 8, sta: 4 }, sellValue: 900, requiredClass: [...LEATHER] },
  deathward_helm: { id: 'deathward_helm', name: 'Deathward Helm', kind: 'armor', slot: 'helmet', quality: 'uncommon', stats: { armor: 160, sta: 9, str: 5 }, sellValue: 1100, requiredClass: [...PLATE] },
  deathward_hood: { id: 'deathward_hood', name: 'Deathward Hood', kind: 'armor', slot: 'helmet', quality: 'uncommon', stats: { armor: 42, int: 9, spi: 5 }, sellValue: 1100, requiredClass: [...CLOTH] },
  deathward_cowl: { id: 'deathward_cowl', name: 'Deathward Cowl', kind: 'armor', slot: 'helmet', quality: 'uncommon', stats: { armor: 95, agi: 9, sta: 4 }, sellValue: 1100, requiredClass: [...LEATHER] },
  gravelord_pauldrons: { id: 'gravelord_pauldrons', name: 'Gravelord Pauldrons', kind: 'armor', slot: 'shoulder', quality: 'rare', stats: { armor: 175, sta: 11, str: 7 }, sellValue: 1600, requiredClass: [...PLATE] },
  gravelord_amice: { id: 'gravelord_amice', name: 'Gravelord Amice', kind: 'armor', slot: 'shoulder', quality: 'rare', stats: { armor: 46, int: 11, spi: 6 }, sellValue: 1600, requiredClass: [...CLOTH] },
  gravelord_spaulders: { id: 'gravelord_spaulders', name: 'Gravelord Spaulders', kind: 'armor', slot: 'shoulder', quality: 'rare', stats: { armor: 100, agi: 11, sta: 5 }, sellValue: 1600, requiredClass: [...LEATHER] },

  // === Tier 0.5 sets (rare), sold by Quartermaster Henning, gated by Dawn standing ===
  // --- Dawnguard Battlegear (plate) ---
  dawnguard_sabatons: { id: 'dawnguard_sabatons', name: 'Dawnguard Sabatons', kind: 'armor', slot: 'feet', quality: 'rare', stats: { armor: 150, sta: 8, str: 5 }, sellValue: 1500, buyValue: 6000, requiredClass: [...PLATE] },
  dawnguard_gauntlets: { id: 'dawnguard_gauntlets', name: 'Dawnguard Gauntlets', kind: 'armor', slot: 'gloves', quality: 'rare', stats: { armor: 140, sta: 7, str: 6 }, sellValue: 1500, buyValue: 6000, requiredClass: [...PLATE] },
  dawnguard_girdle: { id: 'dawnguard_girdle', name: 'Dawnguard Girdle', kind: 'armor', slot: 'waist', quality: 'rare', stats: { armor: 145, sta: 8, str: 5 }, sellValue: 1500, buyValue: 6000, requiredClass: [...PLATE] },
  dawnguard_greathelm: { id: 'dawnguard_greathelm', name: 'Dawnguard Greathelm', kind: 'armor', slot: 'helmet', quality: 'rare', stats: { armor: 190, sta: 11, str: 7 }, sellValue: 2400, buyValue: 9000, requiredClass: [...PLATE] },
  dawnguard_legplates: { id: 'dawnguard_legplates', name: 'Dawnguard Legplates', kind: 'armor', slot: 'legs', quality: 'rare', stats: { armor: 210, sta: 12, str: 8 }, sellValue: 2400, buyValue: 9000, requiredClass: [...PLATE] },
  dawnguard_pauldrons: { id: 'dawnguard_pauldrons', name: 'Dawnguard Pauldrons', kind: 'armor', slot: 'shoulder', quality: 'rare', stats: { armor: 175, sta: 10, str: 7 }, sellValue: 3200, buyValue: 12000, requiredClass: [...PLATE] },
  dawnguard_breastplate: { id: 'dawnguard_breastplate', name: 'Dawnguard Breastplate', kind: 'armor', slot: 'chest', quality: 'rare', stats: { armor: 235, sta: 14, str: 9 }, sellValue: 3200, buyValue: 12000, requiredClass: [...PLATE] },
  dawnguard_blade: { id: 'dawnguard_blade', name: 'Dawnguard Blade', kind: 'weapon', slot: 'mainhand', quality: 'rare', weapon: { min: 34, max: 52, speed: 2.5 }, stats: { str: 10, sta: 5 }, sellValue: 5000, buyValue: 18000, requiredClass: [...PLATE] },
  // --- Vestments of the Dawn (cloth) ---
  dawn_slippers: { id: 'dawn_slippers', name: 'Dawn Slippers', kind: 'armor', slot: 'feet', quality: 'rare', stats: { armor: 40, int: 8, spi: 5 }, sellValue: 1500, buyValue: 6000, requiredClass: [...CLOTH] },
  dawn_handwraps: { id: 'dawn_handwraps', name: 'Dawn Handwraps', kind: 'armor', slot: 'gloves', quality: 'rare', stats: { armor: 36, int: 8, spi: 4 }, sellValue: 1500, buyValue: 6000, requiredClass: [...CLOTH] },
  dawn_cord: { id: 'dawn_cord', name: 'Dawn Cord', kind: 'armor', slot: 'waist', quality: 'rare', stats: { armor: 38, int: 8, spi: 4 }, sellValue: 1500, buyValue: 6000, requiredClass: [...CLOTH] },
  dawn_cowl: { id: 'dawn_cowl', name: 'Dawn Cowl', kind: 'armor', slot: 'helmet', quality: 'rare', stats: { armor: 52, int: 11, spi: 6 }, sellValue: 2400, buyValue: 9000, requiredClass: [...CLOTH] },
  dawn_leggings: { id: 'dawn_leggings', name: 'Dawn Leggings', kind: 'armor', slot: 'legs', quality: 'rare', stats: { armor: 58, int: 12, spi: 7 }, sellValue: 2400, buyValue: 9000, requiredClass: [...CLOTH] },
  dawn_mantle: { id: 'dawn_mantle', name: 'Dawn Mantle', kind: 'armor', slot: 'shoulder', quality: 'rare', stats: { armor: 48, int: 10, spi: 6 }, sellValue: 3200, buyValue: 12000, requiredClass: [...CLOTH] },
  dawn_robe: { id: 'dawn_robe', name: 'Dawn Robe', kind: 'armor', slot: 'chest', quality: 'rare', stats: { armor: 66, int: 14, spi: 8 }, sellValue: 3200, buyValue: 12000, requiredClass: [...CLOTH] },
  dawn_scepter: { id: 'dawn_scepter', name: 'Scepter of the Dawn', kind: 'weapon', slot: 'mainhand', quality: 'rare', weapon: { min: 28, max: 43, speed: 2.6 }, stats: { int: 10, spi: 5 }, sellValue: 5000, buyValue: 18000, requiredClass: [...CLOTH] },
  // --- Dawnstalker Armor (leather) ---
  dawnstalker_treads: { id: 'dawnstalker_treads', name: 'Dawnstalker Treads', kind: 'armor', slot: 'feet', quality: 'rare', stats: { armor: 90, agi: 8, sta: 4 }, sellValue: 1500, buyValue: 6000, requiredClass: [...LEATHER] },
  dawnstalker_grips: { id: 'dawnstalker_grips', name: 'Dawnstalker Grips', kind: 'armor', slot: 'gloves', quality: 'rare', stats: { armor: 85, agi: 8, sta: 3 }, sellValue: 1500, buyValue: 6000, requiredClass: [...LEATHER] },
  dawnstalker_belt: { id: 'dawnstalker_belt', name: 'Dawnstalker Belt', kind: 'armor', slot: 'waist', quality: 'rare', stats: { armor: 88, agi: 8, sta: 4 }, sellValue: 1500, buyValue: 6000, requiredClass: [...LEATHER] },
  dawnstalker_mask: { id: 'dawnstalker_mask', name: 'Dawnstalker Mask', kind: 'armor', slot: 'helmet', quality: 'rare', stats: { armor: 115, agi: 11, sta: 5 }, sellValue: 2400, buyValue: 9000, requiredClass: [...LEATHER] },
  dawnstalker_legguards: { id: 'dawnstalker_legguards', name: 'Dawnstalker Legguards', kind: 'armor', slot: 'legs', quality: 'rare', stats: { armor: 125, agi: 12, sta: 6 }, sellValue: 2400, buyValue: 9000, requiredClass: [...LEATHER] },
  dawnstalker_spaulders: { id: 'dawnstalker_spaulders', name: 'Dawnstalker Spaulders', kind: 'armor', slot: 'shoulder', quality: 'rare', stats: { armor: 105, agi: 10, sta: 5 }, sellValue: 3200, buyValue: 12000, requiredClass: [...LEATHER] },
  dawnstalker_tunic: { id: 'dawnstalker_tunic', name: 'Dawnstalker Tunic', kind: 'armor', slot: 'chest', quality: 'rare', stats: { armor: 135, agi: 14, sta: 7 }, sellValue: 3200, buyValue: 12000, requiredClass: [...LEATHER] },
  dawnstalker_dagger: { id: 'dawnstalker_dagger', name: 'Dawnstalker Dagger', kind: 'weapon', slot: 'mainhand', quality: 'rare', weapon: { min: 31, max: 47, speed: 1.8 }, stats: { agi: 10, sta: 5 }, sellValue: 5000, buyValue: 18000, requiredClass: [...LEATHER] },
};

export const ZONE4_PROPS: ZonePropsDef = {
  buildings: [],
  wells: [],
  stalls: [],
  mines: [],
  docks: [],
  tents: [],
  crates: [],
  campfires: [],
  mudHuts: [],
  ruinRings: [],
  fences: [],
  graveyards: [],
  delveMarkers: [],
};
