// GENERATED by scripts/wiki/build_content.mjs from src/sim/content. Do not edit by hand.
// Regenerate with `npm run wiki:content`; tests/guide.test.ts checks it stays fresh.
// Spec names and ability names are the English sim source (proper nouns); all other
// Guide copy is localized via guide.* t() keys, and rich spec/mastery prose resolves
// live through src/ui/talent_i18n.ts. No balance numbers or instanced spoilers here.

export type GuideRole = 'tank' | 'healer' | 'dps';
export type GuideResource = 'rage' | 'mana' | 'energy';

export interface GuideAbilityRef { id: string; name: string; }
export interface GuideClassSpec { id: string; name: string; role: GuideRole; signature: string; }

// Interactive 3D model data, mirrored from the renderer's VisualDef manifest. The Guide's
// standalone viewer builds the model from one GLB on demand; entities reference a model by
// visual key into GUIDE_MODELS and carry their own tint color.
export interface GuideModelAttach { url: string; bone: string; position?: [number, number, number]; rotationY?: number; gripRef?: string; }
export interface GuideModelWeaponFix { node: string; rotX?: number; rotY?: number; rotZ?: number; }
export interface GuideModelSpec {
  url: string;
  idle: string | null;
  height: number;
  yaw?: number;
  hover?: number;
  show?: string[];
  attach?: GuideModelAttach[];
  weaponFix?: GuideModelWeaponFix[];
  tintStrength?: number;
}

export interface GuideClassInfo {
  id: string;
  color: string;
  resource: GuideResource;
  roles: GuideRole[];
  specs: GuideClassSpec[];
  signatureAbilities: GuideAbilityRef[];
  abilities: GuideAbilityRef[];
  model: string;
  tint?: string;
  /** Pre-rendered transparent still (public/guide-stills/), the default poster. */
  still?: string;
}

export interface GuideZoneInfo {
  id: string;
  name: string;
  min: number;
  max: number;
  biome: string;
  hub: string;
  pois: string[];
  welcome: string;
}

export interface GuideDungeon {
  id: string;
  isRaid: boolean;
  suggestedPlayers: number;
  min: number | null;
  max: number | null;
  name?: string;
}

export interface GuideWarlockPet { id: string; name: string; model: string; tint?: string; still?: string; }

export interface GuideCreature { name: string; min: number; max: number; rare: boolean; templateId: string; model: string; tint?: string; still?: string; }
export interface GuideFamily { family: string; creatures: GuideCreature[]; }

export interface GuideDelveKeeper { name: string; title: string; }
export interface GuideDelveCompanion { name: string; role: string; }
export interface GuideDelve {
  id: string;
  name: string;
  theme: string;
  minLevel: number;
  suggestedPlayers: number;
  keeper?: GuideDelveKeeper;
  companion?: GuideDelveCompanion;
  tiers: string[];
  affixes: string[];
}

export const GUIDE_CLASSES: GuideClassInfo[] = [
  {
    "id": "warrior",
    "color": "#d67a54",
    "resource": "rage",
    "roles": [
      "tank",
      "dps"
    ],
    "specs": [
      {
        "id": "arms",
        "name": "Arms",
        "role": "dps",
        "signature": "mortal_strike"
      },
      {
        "id": "fury",
        "name": "Fury",
        "role": "dps",
        "signature": "bloodthirst"
      },
      {
        "id": "prot",
        "name": "Protection",
        "role": "tank",
        "signature": "shield_slam"
      }
    ],
    "signatureAbilities": [
      {
        "id": "heroic_strike",
        "name": "Heroic Strike"
      },
      {
        "id": "battle_shout",
        "name": "Battle Shout"
      },
      {
        "id": "commanding_shout",
        "name": "Commanding Shout"
      },
      {
        "id": "charge",
        "name": "Charge"
      },
      {
        "id": "rend",
        "name": "Rend"
      },
      {
        "id": "thunder_clap",
        "name": "Thunder Clap"
      }
    ],
    "abilities": [
      {
        "id": "heroic_strike",
        "name": "Heroic Strike"
      },
      {
        "id": "battle_shout",
        "name": "Battle Shout"
      },
      {
        "id": "commanding_shout",
        "name": "Commanding Shout"
      },
      {
        "id": "charge",
        "name": "Charge"
      },
      {
        "id": "rend",
        "name": "Rend"
      },
      {
        "id": "thunder_clap",
        "name": "Thunder Clap"
      },
      {
        "id": "hamstring",
        "name": "Hamstring"
      },
      {
        "id": "bloodrage",
        "name": "Bloodrage"
      },
      {
        "id": "overpower",
        "name": "Overpower"
      },
      {
        "id": "execute",
        "name": "Execute"
      },
      {
        "id": "slam",
        "name": "Slam"
      },
      {
        "id": "cleave",
        "name": "Cleave"
      },
      {
        "id": "defensive_stance",
        "name": "Defensive Stance"
      },
      {
        "id": "demoralizing_shout",
        "name": "Demoralizing Shout"
      },
      {
        "id": "sunder_armor",
        "name": "Sunder Armor"
      },
      {
        "id": "taunt",
        "name": "Taunt"
      },
      {
        "id": "ironhold",
        "name": "Ironhold"
      }
    ],
    "model": "player_warrior",
    "still": "/guide-stills/player_warrior.webp"
  },
  {
    "id": "paladin",
    "color": "#f58ca0",
    "resource": "mana",
    "roles": [
      "tank",
      "healer",
      "dps"
    ],
    "specs": [
      {
        "id": "holy",
        "name": "Holy",
        "role": "healer",
        "signature": "flash_of_light"
      },
      {
        "id": "protection",
        "name": "Protection",
        "role": "tank",
        "signature": "righteous_fury"
      },
      {
        "id": "retribution",
        "name": "Retribution",
        "role": "dps",
        "signature": "judgement"
      }
    ],
    "signatureAbilities": [
      {
        "id": "seal_of_righteousness",
        "name": "Seal of Righteousness"
      },
      {
        "id": "holy_light",
        "name": "Holy Light"
      },
      {
        "id": "devotion_aura",
        "name": "Devotion Aura"
      },
      {
        "id": "judgement",
        "name": "Judgement"
      },
      {
        "id": "blessing_of_might",
        "name": "Blessing of Might"
      },
      {
        "id": "divine_protection",
        "name": "Divine Protection"
      }
    ],
    "abilities": [
      {
        "id": "seal_of_righteousness",
        "name": "Seal of Righteousness"
      },
      {
        "id": "holy_light",
        "name": "Holy Light"
      },
      {
        "id": "devotion_aura",
        "name": "Devotion Aura"
      },
      {
        "id": "judgement",
        "name": "Judgement"
      },
      {
        "id": "blessing_of_might",
        "name": "Blessing of Might"
      },
      {
        "id": "divine_protection",
        "name": "Divine Protection"
      },
      {
        "id": "hammer_of_justice",
        "name": "Hammer of Justice"
      },
      {
        "id": "lay_on_hands",
        "name": "Lay on Hands"
      },
      {
        "id": "flash_of_light",
        "name": "Flash of Light"
      },
      {
        "id": "exorcism",
        "name": "Exorcism"
      },
      {
        "id": "consecration",
        "name": "Consecration"
      },
      {
        "id": "righteous_fury",
        "name": "Righteous Fury"
      },
      {
        "id": "retribution_aura",
        "name": "Retribution Aura"
      }
    ],
    "model": "player_paladin",
    "still": "/guide-stills/player_paladin.webp"
  },
  {
    "id": "hunter",
    "color": "#a6d84f",
    "resource": "mana",
    "roles": [
      "dps"
    ],
    "specs": [
      {
        "id": "beast_mastery",
        "name": "Beast Mastery",
        "role": "dps",
        "signature": "tame_beast"
      },
      {
        "id": "marksmanship",
        "name": "Marksmanship",
        "role": "dps",
        "signature": "aimed_shot"
      },
      {
        "id": "survival",
        "name": "Survival",
        "role": "dps",
        "signature": "wing_clip"
      }
    ],
    "signatureAbilities": [
      {
        "id": "raptor_strike",
        "name": "Raptor Strike"
      },
      {
        "id": "aspect_of_the_hawk",
        "name": "Aspect of the Hawk"
      },
      {
        "id": "serpent_sting",
        "name": "Serpent Sting"
      },
      {
        "id": "arcane_shot",
        "name": "Arcane Shot"
      },
      {
        "id": "concussive_shot",
        "name": "Concussive Shot"
      },
      {
        "id": "mongoose_bite",
        "name": "Mongoose Bite"
      }
    ],
    "abilities": [
      {
        "id": "raptor_strike",
        "name": "Raptor Strike"
      },
      {
        "id": "aspect_of_the_hawk",
        "name": "Aspect of the Hawk"
      },
      {
        "id": "serpent_sting",
        "name": "Serpent Sting"
      },
      {
        "id": "arcane_shot",
        "name": "Arcane Shot"
      },
      {
        "id": "concussive_shot",
        "name": "Concussive Shot"
      },
      {
        "id": "mongoose_bite",
        "name": "Mongoose Bite"
      },
      {
        "id": "wing_clip",
        "name": "Wing Clip"
      },
      {
        "id": "tame_beast",
        "name": "Tame Beast"
      },
      {
        "id": "dismiss_pet",
        "name": "Dismiss Pet"
      },
      {
        "id": "revive_pet",
        "name": "Revive Pet"
      },
      {
        "id": "aspect_of_the_monkey",
        "name": "Aspect of the Monkey"
      },
      {
        "id": "aspect_of_the_cheetah",
        "name": "Aspect of the Cheetah"
      },
      {
        "id": "aimed_shot",
        "name": "Aimed Shot"
      },
      {
        "id": "rapid_fire",
        "name": "Rapid Fire"
      }
    ],
    "model": "player_hunter",
    "still": "/guide-stills/player_hunter.webp"
  },
  {
    "id": "rogue",
    "color": "#fcee58",
    "resource": "energy",
    "roles": [
      "dps"
    ],
    "specs": [
      {
        "id": "assassination",
        "name": "Assassination",
        "role": "dps",
        "signature": "eviscerate"
      },
      {
        "id": "combat",
        "name": "Combat",
        "role": "dps",
        "signature": "adrenaline_rush"
      },
      {
        "id": "subtlety",
        "name": "Subtlety",
        "role": "dps",
        "signature": "ambush"
      }
    ],
    "signatureAbilities": [
      {
        "id": "sinister_strike",
        "name": "Sinister Strike"
      },
      {
        "id": "eviscerate",
        "name": "Eviscerate"
      },
      {
        "id": "garrote",
        "name": "Garrote"
      },
      {
        "id": "backstab",
        "name": "Backstab"
      },
      {
        "id": "gouge",
        "name": "Gouge"
      },
      {
        "id": "cheap_shot",
        "name": "Cheap Shot"
      }
    ],
    "abilities": [
      {
        "id": "sinister_strike",
        "name": "Sinister Strike"
      },
      {
        "id": "eviscerate",
        "name": "Eviscerate"
      },
      {
        "id": "garrote",
        "name": "Garrote"
      },
      {
        "id": "backstab",
        "name": "Backstab"
      },
      {
        "id": "gouge",
        "name": "Gouge"
      },
      {
        "id": "cheap_shot",
        "name": "Cheap Shot"
      },
      {
        "id": "evasion",
        "name": "Evasion"
      },
      {
        "id": "sap",
        "name": "Sap"
      },
      {
        "id": "slice_and_dice",
        "name": "Slice and Dice"
      },
      {
        "id": "sprint",
        "name": "Sprint"
      },
      {
        "id": "crippling_poison",
        "name": "Crippling Poison"
      },
      {
        "id": "kidney_shot",
        "name": "Kidney Shot"
      },
      {
        "id": "expose_armor",
        "name": "Expose Armor"
      },
      {
        "id": "ambush",
        "name": "Ambush"
      },
      {
        "id": "rupture",
        "name": "Rupture"
      },
      {
        "id": "vanish",
        "name": "Vanish"
      },
      {
        "id": "instant_poison",
        "name": "Instant Poison"
      },
      {
        "id": "adrenaline_rush",
        "name": "Adrenaline Rush"
      },
      {
        "id": "deadly_poison",
        "name": "Deadly Poison"
      },
      {
        "id": "blind",
        "name": "Blind"
      },
      {
        "id": "stealth",
        "name": "Stealth"
      }
    ],
    "model": "player_rogue",
    "still": "/guide-stills/player_rogue.webp"
  },
  {
    "id": "priest",
    "color": "#c6d4f0",
    "resource": "mana",
    "roles": [
      "healer",
      "dps"
    ],
    "specs": [
      {
        "id": "discipline",
        "name": "Discipline",
        "role": "healer",
        "signature": "power_word_shield"
      },
      {
        "id": "holy",
        "name": "Holy",
        "role": "healer",
        "signature": "flash_heal"
      },
      {
        "id": "shadow",
        "name": "Shadow",
        "role": "dps",
        "signature": "mind_flay"
      }
    ],
    "signatureAbilities": [
      {
        "id": "smite",
        "name": "Smite"
      },
      {
        "id": "lesser_heal",
        "name": "Lesser Heal"
      },
      {
        "id": "power_word_fortitude",
        "name": "Power Word: Fortitude"
      },
      {
        "id": "shadow_word_pain",
        "name": "Shadow Word: Pain"
      },
      {
        "id": "power_word_shield",
        "name": "Power Word: Shield"
      },
      {
        "id": "renew",
        "name": "Renew"
      }
    ],
    "abilities": [
      {
        "id": "smite",
        "name": "Smite"
      },
      {
        "id": "lesser_heal",
        "name": "Lesser Heal"
      },
      {
        "id": "power_word_fortitude",
        "name": "Power Word: Fortitude"
      },
      {
        "id": "shadow_word_pain",
        "name": "Shadow Word: Pain"
      },
      {
        "id": "power_word_shield",
        "name": "Power Word: Shield"
      },
      {
        "id": "renew",
        "name": "Renew"
      },
      {
        "id": "mind_blast",
        "name": "Mind Blast"
      },
      {
        "id": "heal",
        "name": "Heal"
      },
      {
        "id": "mind_flay",
        "name": "Mind Flay"
      },
      {
        "id": "flash_heal",
        "name": "Flash Heal"
      }
    ],
    "model": "player_priest",
    "tint": "#f0e9d6",
    "still": "/guide-stills/player_priest__f0e9d6.webp"
  },
  {
    "id": "shaman",
    "color": "#4e8aea",
    "resource": "mana",
    "roles": [
      "healer",
      "dps"
    ],
    "specs": [
      {
        "id": "elemental",
        "name": "Elemental",
        "role": "dps",
        "signature": "lightning_bolt"
      },
      {
        "id": "enhancement",
        "name": "Enhancement",
        "role": "dps",
        "signature": "stormstrike"
      },
      {
        "id": "restoration",
        "name": "Restoration",
        "role": "healer",
        "signature": "healing_wave"
      }
    ],
    "signatureAbilities": [
      {
        "id": "lightning_bolt",
        "name": "Lightning Bolt"
      },
      {
        "id": "rockbiter_weapon",
        "name": "Rockbiter Weapon"
      },
      {
        "id": "healing_wave",
        "name": "Healing Wave"
      },
      {
        "id": "earth_shock",
        "name": "Earth Shock"
      },
      {
        "id": "lightning_shield",
        "name": "Lightning Shield"
      },
      {
        "id": "flame_shock",
        "name": "Flame Shock"
      }
    ],
    "abilities": [
      {
        "id": "lightning_bolt",
        "name": "Lightning Bolt"
      },
      {
        "id": "rockbiter_weapon",
        "name": "Rockbiter Weapon"
      },
      {
        "id": "healing_wave",
        "name": "Healing Wave"
      },
      {
        "id": "earth_shock",
        "name": "Earth Shock"
      },
      {
        "id": "lightning_shield",
        "name": "Lightning Shield"
      },
      {
        "id": "flame_shock",
        "name": "Flame Shock"
      },
      {
        "id": "flametongue_weapon",
        "name": "Flametongue Weapon"
      },
      {
        "id": "frost_shock",
        "name": "Frost Shock"
      },
      {
        "id": "frostbrand_weapon",
        "name": "Frostbrand Weapon"
      },
      {
        "id": "ghost_wolf",
        "name": "Ghost Wolf"
      },
      {
        "id": "stormstrike",
        "name": "Stormstrike"
      }
    ],
    "model": "player_shaman",
    "tint": "#6f8fc9",
    "still": "/guide-stills/player_shaman__6f8fc9.webp"
  },
  {
    "id": "mage",
    "color": "#33c1f1",
    "resource": "mana",
    "roles": [
      "dps"
    ],
    "specs": [
      {
        "id": "arcane",
        "name": "Arcane",
        "role": "dps",
        "signature": "arcane_missiles"
      },
      {
        "id": "fire",
        "name": "Fire",
        "role": "dps",
        "signature": "scorch"
      },
      {
        "id": "frost",
        "name": "Frost",
        "role": "dps",
        "signature": "ice_barrier"
      }
    ],
    "signatureAbilities": [
      {
        "id": "fireball",
        "name": "Fireball"
      },
      {
        "id": "frost_armor",
        "name": "Frost Armor"
      },
      {
        "id": "arcane_intellect",
        "name": "Arcane Intellect"
      },
      {
        "id": "frostbolt",
        "name": "Frostbolt"
      },
      {
        "id": "conjure_water",
        "name": "Conjure Water"
      },
      {
        "id": "conjure_food",
        "name": "Conjure Food"
      }
    ],
    "abilities": [
      {
        "id": "fireball",
        "name": "Fireball"
      },
      {
        "id": "frost_armor",
        "name": "Frost Armor"
      },
      {
        "id": "arcane_intellect",
        "name": "Arcane Intellect"
      },
      {
        "id": "frostbolt",
        "name": "Frostbolt"
      },
      {
        "id": "conjure_water",
        "name": "Conjure Water"
      },
      {
        "id": "conjure_food",
        "name": "Conjure Food"
      },
      {
        "id": "fire_blast",
        "name": "Fire Blast"
      },
      {
        "id": "arcane_missiles",
        "name": "Arcane Missiles"
      },
      {
        "id": "polymorph",
        "name": "Polymorph"
      },
      {
        "id": "frost_nova",
        "name": "Frost Nova"
      },
      {
        "id": "arcane_explosion",
        "name": "Arcane Explosion"
      },
      {
        "id": "scorch",
        "name": "Scorch"
      },
      {
        "id": "ice_barrier",
        "name": "Ice Barrier"
      },
      {
        "id": "pyroblast",
        "name": "Pyroblast"
      }
    ],
    "model": "player_mage",
    "still": "/guide-stills/player_mage.webp"
  },
  {
    "id": "warlock",
    "color": "#a785e6",
    "resource": "mana",
    "roles": [
      "dps"
    ],
    "specs": [
      {
        "id": "affliction",
        "name": "Affliction",
        "role": "dps",
        "signature": "drain_life"
      },
      {
        "id": "demonology",
        "name": "Demonology",
        "role": "dps",
        "signature": "demon_skin"
      },
      {
        "id": "destruction",
        "name": "Destruction",
        "role": "dps",
        "signature": "shadowburn"
      }
    ],
    "signatureAbilities": [
      {
        "id": "shadow_bolt",
        "name": "Shadow Bolt"
      },
      {
        "id": "summon_imp",
        "name": "Summon Imp"
      },
      {
        "id": "demon_skin",
        "name": "Demon Skin"
      },
      {
        "id": "immolate",
        "name": "Immolate"
      },
      {
        "id": "corruption",
        "name": "Corruption"
      },
      {
        "id": "life_tap",
        "name": "Life Tap"
      }
    ],
    "abilities": [
      {
        "id": "shadow_bolt",
        "name": "Shadow Bolt"
      },
      {
        "id": "summon_imp",
        "name": "Summon Imp"
      },
      {
        "id": "demon_skin",
        "name": "Demon Skin"
      },
      {
        "id": "immolate",
        "name": "Immolate"
      },
      {
        "id": "corruption",
        "name": "Corruption"
      },
      {
        "id": "life_tap",
        "name": "Life Tap"
      },
      {
        "id": "summon_voidwalker",
        "name": "Summon Voidwalker"
      },
      {
        "id": "curse_of_agony",
        "name": "Curse of Agony"
      },
      {
        "id": "drain_life",
        "name": "Drain Life"
      },
      {
        "id": "fear",
        "name": "Fear"
      },
      {
        "id": "searing_pain",
        "name": "Searing Pain"
      },
      {
        "id": "shadowburn",
        "name": "Shadowburn"
      },
      {
        "id": "summon_succubus",
        "name": "Summon Succubus"
      },
      {
        "id": "summon_felhunter",
        "name": "Summon Felhunter"
      },
      {
        "id": "summon_felguard",
        "name": "Summon Felguard"
      },
      {
        "id": "summon_infernal",
        "name": "Summon Infernal"
      },
      {
        "id": "summon_doomguard",
        "name": "Summon Doomguard"
      }
    ],
    "model": "player_warlock",
    "tint": "#8d5fd3",
    "still": "/guide-stills/player_warlock__8d5fd3.webp"
  },
  {
    "id": "druid",
    "color": "#ff8c1a",
    "resource": "mana",
    "roles": [
      "tank",
      "healer",
      "dps"
    ],
    "specs": [
      {
        "id": "balance",
        "name": "Balance",
        "role": "dps",
        "signature": "starfire"
      },
      {
        "id": "feral",
        "name": "Feral",
        "role": "tank",
        "signature": "bear_form"
      },
      {
        "id": "restoration",
        "name": "Restoration",
        "role": "healer",
        "signature": "regrowth"
      }
    ],
    "signatureAbilities": [
      {
        "id": "wrath",
        "name": "Wrath"
      },
      {
        "id": "healing_touch",
        "name": "Healing Touch"
      },
      {
        "id": "mark_of_the_wild",
        "name": "Mark of the Wild"
      },
      {
        "id": "moonfire",
        "name": "Moonfire"
      },
      {
        "id": "rejuvenation",
        "name": "Rejuvenation"
      },
      {
        "id": "thorns",
        "name": "Thorns"
      }
    ],
    "abilities": [
      {
        "id": "wrath",
        "name": "Wrath"
      },
      {
        "id": "healing_touch",
        "name": "Healing Touch"
      },
      {
        "id": "mark_of_the_wild",
        "name": "Mark of the Wild"
      },
      {
        "id": "moonfire",
        "name": "Moonfire"
      },
      {
        "id": "rejuvenation",
        "name": "Rejuvenation"
      },
      {
        "id": "thorns",
        "name": "Thorns"
      },
      {
        "id": "entangling_roots",
        "name": "Entangling Roots"
      },
      {
        "id": "bear_form",
        "name": "Bear Form"
      },
      {
        "id": "bear_charge",
        "name": "Bear Charge"
      },
      {
        "id": "maul",
        "name": "Maul"
      },
      {
        "id": "growl",
        "name": "Growl"
      },
      {
        "id": "demoralizing_roar",
        "name": "Demoralizing Roar"
      },
      {
        "id": "cat_form",
        "name": "Wolf Form"
      },
      {
        "id": "prowl",
        "name": "Prowl"
      },
      {
        "id": "rake",
        "name": "Rake"
      },
      {
        "id": "claw",
        "name": "Claw"
      },
      {
        "id": "regrowth",
        "name": "Regrowth"
      },
      {
        "id": "ferocious_bite",
        "name": "Ferocious Bite"
      },
      {
        "id": "barkskin",
        "name": "Barkskin"
      },
      {
        "id": "swipe",
        "name": "Swipe"
      },
      {
        "id": "starfire",
        "name": "Starfire"
      },
      {
        "id": "travel_form",
        "name": "Travel Form"
      },
      {
        "id": "enrage",
        "name": "Enrage"
      },
      {
        "id": "bash",
        "name": "Bash"
      },
      {
        "id": "faerie_fire",
        "name": "Faerie Fire"
      },
      {
        "id": "hibernate",
        "name": "Hibernate"
      },
      {
        "id": "dash",
        "name": "Dash"
      },
      {
        "id": "pounce",
        "name": "Pounce"
      },
      {
        "id": "insect_swarm",
        "name": "Insect Swarm"
      },
      {
        "id": "tigers_fury",
        "name": "Tiger's Fury"
      },
      {
        "id": "rip",
        "name": "Rip"
      },
      {
        "id": "primal_reflexes",
        "name": "Primal Reflexes"
      }
    ],
    "model": "player_druid",
    "still": "/guide-stills/player_druid.webp"
  }
];

export const GUIDE_ZONES: GuideZoneInfo[] = [
  {
    "id": "eastbrook_vale",
    "name": "Eastbrook Vale",
    "min": 1,
    "max": 7,
    "biome": "vale",
    "hub": "Eastbrook",
    "pois": [
      "Eastbrook",
      "Wolf Run",
      "Boar Meadow",
      "Mirror Lake",
      "Webwood",
      "Copper Dig",
      "Bandit Camp",
      "Fallen Chapel",
      "Reliquary Hill",
      "Brightwood Glade"
    ],
    "welcome": "Find Marshal Redbrook in town — he has work for you."
  },
  {
    "id": "mirefen_marsh",
    "name": "Mirefen Marsh",
    "min": 6,
    "max": 13,
    "biome": "marsh",
    "hub": "Fenbridge",
    "pois": [
      "Fenbridge",
      "Prowler Reeds",
      "Deepfen Shallows",
      "Widow Thicket",
      "Drowned Chapel",
      "Troll Mounds",
      "Gravecaller Encampment",
      "The Sunken Bastion"
    ],
    "welcome": "Report to Warden Fenwick at the Fenbridge gate."
  },
  {
    "id": "thornpeak_heights",
    "name": "Thornpeak Heights",
    "min": 13,
    "max": 20,
    "biome": "peaks",
    "hub": "Highwatch",
    "pois": [
      "Highwatch",
      "Stalker Ridge",
      "Deeprock Burrows",
      "Ogre Foothills",
      "Drogmar's War-Camp",
      "Stormcrag",
      "The Glimmermere",
      "Wyrmcult Tents",
      "Revenant Fields",
      "Gravewyrm Sanctum"
    ],
    "welcome": "Captain Thessaly holds the wall at Highwatch — barely."
  },
  {
    "id": "veiled_hollow",
    "name": "The Veiled Hollow",
    "min": 15,
    "max": 20,
    "biome": "dusk",
    "hub": "Eldergleam",
    "pois": [
      "Eldergleam",
      "Duskfall Cave",
      "Duskfall Overlook",
      "Elder Grove",
      "Starfall Basin",
      "The Sunken Court",
      "Crystalline Shallows",
      "The Gleaming Deep"
    ],
    "welcome": "The air hums with old magic. Seek Keeper Saelwyn beneath the great tree of Eldergleam."
  },
  {
    "id": "frostveil",
    "name": "The Frostveil Reach",
    "min": 17,
    "max": 20,
    "biome": "frost",
    "hub": "Icemantle",
    "pois": [
      "Icemantle",
      "The Snowline",
      "Glacier Tarn",
      "The Aurora Steps",
      "The Shiverfen",
      "The Howling Terraces"
    ],
    "welcome": "Snow swallows every sound. Under the dancing lights, the cold itself feels awake."
  },
  {
    "id": "farshore_isle",
    "name": "The Farshore",
    "min": 3,
    "max": 7,
    "biome": "vale",
    "hub": "Gullhaven",
    "pois": [
      "Gullhaven",
      "The Landing",
      "The Watch Meadow",
      "The Sundered Cliffs",
      "The Riftfields"
    ],
    "welcome": "Cross the sandbar and Gullhaven's bell will find you before the town does. The breaks tear open without warning, and the redoubt holds its shore against whatever pours through. They have been waiting a long while for someone like you."
  },
  {
    "id": "willowfen",
    "name": "The Willowfen",
    "min": 19,
    "max": 20,
    "biome": "fen",
    "hub": "Bridgemere",
    "pois": [
      "Bridgemere",
      "The Amberfen Steps",
      "The Lilymoors",
      "Bogshine Pools",
      "Willowweep",
      "The Drowsy Flats"
    ],
    "welcome": "The fen hums with dragonflies and bees. Cross the bridge into Bridgemere and rest your feet awhile."
  },
  {
    "id": "galecrest",
    "name": "The Galecrest",
    "min": 20,
    "max": 20,
    "biome": "gale",
    "hub": "Wickharbor",
    "pois": [
      "Wickharbor",
      "The Windway",
      "The Howling Downs",
      "The Old Beacon",
      "The Shear",
      "The Wreckfields",
      "The Mirror Tarn"
    ],
    "welcome": "The wind has never once stopped here, and the Old Beacon has never once gone out. Wickharbor asks only that you close the inn door behind you."
  },
  {
    "id": "palmreach",
    "name": "The Palmreach",
    "min": 20,
    "max": 20,
    "biome": "jungle",
    "hub": "Drifthaven",
    "pois": [
      "Drifthaven",
      "The Tanglemouth",
      "The Palmstrand",
      "The Emerald Tangle",
      "The Vinefall",
      "The Sapphire Lagoon",
      "The Sunken Idol"
    ],
    "welcome": "Warm sand, loud birds, and a jungle that eats the horizon. Drifthaven keeps a fire lit on the beach for you."
  },
  {
    "id": "evergarden",
    "name": "The Evergarden",
    "min": 20,
    "max": 20,
    "biome": "garden",
    "hub": "Hedgewick",
    "pois": [
      "Hedgewick",
      "The Garden Gate",
      "The Parterre Walk",
      "Dawnhold Castle",
      "The Petal Pond",
      "The Great Maze",
      "The Fountain Court",
      "The Old Mill",
      "The North Watch",
      "The Lily Basin"
    ],
    "welcome": "Someone is still trimming the hedges, though no gardener has been seen for a hundred years. Mind the maze: it minds you back."
  },
  {
    "id": "nightbloom",
    "name": "The Nightbloom",
    "min": 20,
    "max": 20,
    "biome": "night",
    "hub": "Moonrest",
    "pois": [
      "Moonrest",
      "The Nightgate",
      "The Moonwell",
      "Gloamfield",
      "The Standing Vigil",
      "The Sleepless Barrow"
    ],
    "welcome": "Past the Nightgate the air itself dreams. Follow the flower-light to Moonrest, and mind the sleeping world that hangs in the sky."
  },
  {
    "id": "wraithwood",
    "name": "The Wraithwood",
    "min": 20,
    "max": 20,
    "biome": "haunt",
    "hub": "Gallowmere",
    "pois": [
      "Gallowmere",
      "The Crowgate",
      "Widow's Thicket",
      "The Hanging Glade",
      "The Mournstone Chapel",
      "The Huntsman's Clearing"
    ],
    "welcome": "The canopy closes over the road like a lid. Keep to the lanterns of Gallowmere, and do not answer if the wood calls your name."
  },
  {
    "id": "amberfall",
    "name": "The Amberfall",
    "min": 18,
    "max": 20,
    "biome": "amber",
    "hub": "Lanternmere",
    "pois": [
      "Lanternmere",
      "The Goldmelt",
      "The Gilded Orchard",
      "Harvest Hollow",
      "The Great Mere",
      "Cindermaple Rise",
      "The Leaning Monolith"
    ],
    "welcome": "Every leaf here burns gold and red, yet none ever fall. The lanterns of Lanternmere are lit for you."
  },
  {
    "id": "drakelands",
    "name": "The Drakelands",
    "min": 16,
    "max": 20,
    "biome": "ember",
    "hub": "Wyrmwatch",
    "pois": [
      "Wyrmwatch",
      "The Gatewood",
      "Cinder Dunes",
      "Trollmoot",
      "The Last Keep",
      "Bloodglass Fields",
      "Drakemaw Caldera"
    ],
    "welcome": "Hot wind rolls off the wastes ahead. Dragons wheel over the Drakemaw, and troll fires burn in the dunes."
  }
];

export const GUIDE_DUNGEONS: GuideDungeon[] = [
  {
    "id": "hollow_crypt",
    "isRaid": false,
    "suggestedPlayers": 5,
    "min": 7,
    "max": 10,
    "name": "The Hollow Crypt"
  },
  {
    "id": "sunken_bastion",
    "isRaid": false,
    "suggestedPlayers": 5,
    "min": 12,
    "max": 13,
    "name": "The Sunken Bastion"
  },
  {
    "id": "drowned_temple",
    "isRaid": false,
    "suggestedPlayers": 5,
    "min": 16,
    "max": 18,
    "name": "The Drowned Temple"
  },
  {
    "id": "gravewyrm_sanctum",
    "isRaid": false,
    "suggestedPlayers": 5,
    "min": 19,
    "max": 20,
    "name": "Gravewyrm Sanctum"
  },
  {
    "id": "claudeholme",
    "isRaid": false,
    "suggestedPlayers": 5,
    "min": 20,
    "max": 22,
    "name": "Claudeholme"
  },
  {
    "id": "cinderforge",
    "isRaid": false,
    "suggestedPlayers": 5,
    "min": 20,
    "max": 22,
    "name": "The Cinderforge"
  },
  {
    "id": "raid",
    "isRaid": true,
    "suggestedPlayers": 10,
    "min": 20,
    "max": 20
  },
  {
    "id": "raid",
    "isRaid": true,
    "suggestedPlayers": 10,
    "min": 20,
    "max": 22
  }
];

export const GUIDE_WARLOCK_PETS: GuideWarlockPet[] = [
  {
    "id": "imp",
    "name": "Imp",
    "model": "mob_demon",
    "tint": "#ff7a2a",
    "still": "/guide-stills/mob_demon__ff7a2a.webp"
  },
  {
    "id": "voidwalker",
    "name": "Voidwalker",
    "model": "mob_demon",
    "tint": "#3a3a6e",
    "still": "/guide-stills/mob_demon__3a3a6e.webp"
  },
  {
    "id": "succubus",
    "name": "Succubus",
    "model": "mob_demon",
    "tint": "#c6469b",
    "still": "/guide-stills/mob_demon__c6469b.webp"
  },
  {
    "id": "felhunter",
    "name": "Felhunter",
    "model": "mob_demonalt",
    "tint": "#4a7d4a",
    "still": "/guide-stills/mob_demonalt__4a7d4a.webp"
  },
  {
    "id": "felguard",
    "name": "Felguard",
    "model": "mob_demonalt",
    "tint": "#6e5a2a",
    "still": "/guide-stills/mob_demonalt__6e5a2a.webp"
  },
  {
    "id": "infernal",
    "name": "Infernal",
    "model": "mob_demonalt",
    "tint": "#d24a2a",
    "still": "/guide-stills/mob_demonalt__d24a2a.webp"
  },
  {
    "id": "doomguard",
    "name": "Doomguard",
    "model": "mob_demonalt",
    "tint": "#7a3a8e",
    "still": "/guide-stills/mob_demonalt__7a3a8e.webp"
  }
];

export const GUIDE_FAMILIES: GuideFamily[] = [
  {
    "family": "beast",
    "creatures": [
      {
        "name": "Forest Wolf",
        "min": 1,
        "max": 2,
        "rare": false,
        "templateId": "forest_wolf",
        "model": "mob_wolf",
        "tint": "#7f8c8d",
        "still": "/guide-stills/mob_wolf__7f8c8d.webp"
      },
      {
        "name": "Wild Boar",
        "min": 2,
        "max": 3,
        "rare": false,
        "templateId": "wild_boar",
        "model": "mob_boar",
        "tint": "#935116",
        "still": "/guide-stills/mob_boar__935116.webp"
      },
      {
        "name": "Old Greyjaw",
        "min": 4,
        "max": 4,
        "rare": true,
        "templateId": "old_greyjaw",
        "model": "mob_wolf",
        "tint": "#566061",
        "still": "/guide-stills/mob_wolf__566061.webp"
      },
      {
        "name": "Void Stalker",
        "min": 5,
        "max": 6,
        "rare": false,
        "templateId": "void_stalker",
        "model": "mob_wolf",
        "tint": "#2f2a44",
        "still": "/guide-stills/mob_wolf__2f2a44.webp"
      },
      {
        "name": "Mire Prowler",
        "min": 7,
        "max": 8,
        "rare": false,
        "templateId": "mire_prowler",
        "model": "mob_wolf",
        "tint": "#4d5656",
        "still": "/guide-stills/mob_wolf__4d5656.webp"
      },
      {
        "name": "Bog Bloat",
        "min": 9,
        "max": 11,
        "rare": false,
        "templateId": "bog_bloat",
        "model": "mob_murloc",
        "tint": "#6b8e23",
        "still": "/guide-stills/mob_murloc__6b8e23.webp"
      },
      {
        "name": "Ridge Stalker",
        "min": 13,
        "max": 14,
        "rare": false,
        "templateId": "ridge_stalker",
        "model": "mob_wolf",
        "tint": "#8c8270",
        "still": "/guide-stills/mob_wolf__8c8270.webp"
      },
      {
        "name": "Veiled Doe",
        "min": 14,
        "max": 15,
        "rare": false,
        "templateId": "veiled_doe",
        "model": "mob_wolf",
        "tint": "#cdbfdc",
        "still": "/guide-stills/mob_wolf__cdbfdc.webp"
      },
      {
        "name": "Veiled Stag",
        "min": 15,
        "max": 16,
        "rare": false,
        "templateId": "veiled_stag",
        "model": "mob_wolf",
        "tint": "#b9a3cf",
        "still": "/guide-stills/mob_wolf__b9a3cf.webp"
      },
      {
        "name": "Snowdrift Wolf",
        "min": 17,
        "max": 18,
        "rare": false,
        "templateId": "snowdrift_wolf",
        "model": "mob_wolf",
        "tint": "#eef4f8",
        "still": "/guide-stills/mob_wolf__eef4f8.webp"
      },
      {
        "name": "Gilded Stag",
        "min": 18,
        "max": 19,
        "rare": false,
        "templateId": "gilded_stag",
        "model": "mob_wolf",
        "tint": "#d8a848",
        "still": "/guide-stills/mob_wolf__d8a848.webp"
      },
      {
        "name": "Gloam Fox",
        "min": 18,
        "max": 18,
        "rare": false,
        "templateId": "gloam_fox",
        "model": "mob_wolf",
        "tint": "#d87838",
        "still": "/guide-stills/mob_wolf__d87838.webp"
      },
      {
        "name": "Terrace Howler",
        "min": 19,
        "max": 20,
        "rare": false,
        "templateId": "terrace_howler",
        "model": "mob_wolf",
        "tint": "#9db4c8",
        "still": "/guide-stills/mob_wolf__9db4c8.webp"
      },
      {
        "name": "Gloam Strider",
        "min": 20,
        "max": 20,
        "rare": false,
        "templateId": "gloam_strider",
        "model": "mob_wolf",
        "tint": "#4c4a72",
        "still": "/guide-stills/mob_wolf__4c4a72.webp"
      },
      {
        "name": "Moonfleece Grazer",
        "min": 20,
        "max": 20,
        "rare": false,
        "templateId": "moonfleece_grazer",
        "model": "mob_wolf",
        "tint": "#e6e9f4",
        "still": "/guide-stills/mob_wolf__e6e9f4.webp"
      },
      {
        "name": "Moor Ram",
        "min": 20,
        "max": 20,
        "rare": false,
        "templateId": "moor_ram",
        "model": "mob_wolf",
        "tint": "#d8d0c0",
        "still": "/guide-stills/mob_wolf__d8d0c0.webp"
      },
      {
        "name": "Shoal Scuttler",
        "min": 20,
        "max": 20,
        "rare": false,
        "templateId": "shoal_scuttler",
        "model": "mob_wolf",
        "tint": "#8898a8",
        "still": "/guide-stills/mob_wolf__8898a8.webp"
      },
      {
        "name": "Thicket Boar",
        "min": 20,
        "max": 20,
        "rare": false,
        "templateId": "thicket_boar",
        "model": "mob_wolf",
        "tint": "#6a4e38",
        "still": "/guide-stills/mob_wolf__6a4e38.webp"
      },
      {
        "name": "Tide Scuttler",
        "min": 20,
        "max": 20,
        "rare": false,
        "templateId": "tide_scuttler",
        "model": "mob_wolf",
        "tint": "#e86848",
        "still": "/guide-stills/mob_wolf__e86848.webp"
      },
      {
        "name": "Topiary Stag",
        "min": 20,
        "max": 20,
        "rare": false,
        "templateId": "topiary_stag",
        "model": "mob_wolf",
        "tint": "#3f7e3c",
        "still": "/guide-stills/mob_wolf__3f7e3c.webp"
      },
      {
        "name": "Topiary Wolf",
        "min": 20,
        "max": 20,
        "rare": false,
        "templateId": "topiary_wolf",
        "model": "mob_wolf",
        "tint": "#4a8a4e",
        "still": "/guide-stills/mob_wolf__4a8a4e.webp"
      }
    ]
  },
  {
    "family": "spider",
    "creatures": [
      {
        "name": "Webwood Lurker",
        "min": 2,
        "max": 4,
        "rare": false,
        "templateId": "webwood_spider",
        "model": "mob_spider",
        "tint": "#4a235a",
        "still": "/guide-stills/mob_spider__4a235a.webp"
      },
      {
        "name": "Mirefen Widow",
        "min": 8,
        "max": 10,
        "rare": false,
        "templateId": "mire_widow",
        "model": "mob_spider",
        "tint": "#283747",
        "still": "/guide-stills/mob_spider__283747.webp"
      },
      {
        "name": "Canopy Weaver",
        "min": 20,
        "max": 20,
        "rare": false,
        "templateId": "canopy_weaver",
        "model": "mob_spider",
        "tint": "#4e8a3c",
        "still": "/guide-stills/mob_spider__4e8a3c.webp"
      },
      {
        "name": "Widowsilk Spinner",
        "min": 20,
        "max": 20,
        "rare": false,
        "templateId": "widowsilk_spinner",
        "model": "mob_spider",
        "tint": "#3a3440",
        "still": "/guide-stills/mob_spider__3a3440.webp"
      }
    ]
  },
  {
    "family": "murloc",
    "creatures": [
      {
        "name": "Mudfin Skulker",
        "min": 3,
        "max": 5,
        "rare": false,
        "templateId": "mudfin_murloc",
        "model": "mob_murloc",
        "tint": "#52be80",
        "still": "/guide-stills/mob_murloc__52be80.webp"
      },
      {
        "name": "Deepfen Snapper",
        "min": 8,
        "max": 9,
        "rare": false,
        "templateId": "deepfen_murloc",
        "model": "mob_murloc",
        "tint": "#45b39d",
        "still": "/guide-stills/mob_murloc__45b39d.webp"
      },
      {
        "name": "Glimmermere Wader",
        "min": 15,
        "max": 16,
        "rare": false,
        "templateId": "glimmermere_wader",
        "model": "mob_murloc",
        "tint": "#8fb6c4",
        "still": "/guide-stills/mob_murloc__8fb6c4.webp"
      },
      {
        "name": "Bogtoad",
        "min": 19,
        "max": 20,
        "rare": false,
        "templateId": "bogtoad",
        "model": "mob_murloc",
        "tint": "#7aa848",
        "still": "/guide-stills/mob_murloc__7aa848.webp"
      },
      {
        "name": "Mere Lurker",
        "min": 19,
        "max": 20,
        "rare": false,
        "templateId": "mere_lurker",
        "model": "mob_murloc",
        "tint": "#a8b048",
        "still": "/guide-stills/mob_murloc__a8b048.webp"
      }
    ]
  },
  {
    "family": "kobold",
    "creatures": [
      {
        "name": "Breach Wretch",
        "min": 3,
        "max": 5,
        "rare": false,
        "templateId": "breach_wretch",
        "model": "mob_kobold",
        "tint": "#5a4a78",
        "still": "/guide-stills/mob_kobold__5a4a78.webp"
      },
      {
        "name": "Tunnel Rat Digger",
        "min": 4,
        "max": 6,
        "rare": false,
        "templateId": "tunnel_rat",
        "model": "mob_kobold",
        "tint": "#9c640c",
        "still": "/guide-stills/mob_kobold__9c640c.webp"
      },
      {
        "name": "Deeprock Tunneler",
        "min": 14,
        "max": 15,
        "rare": false,
        "templateId": "deeprock_kobold",
        "model": "mob_kobold",
        "tint": "#9c7a3c",
        "still": "/guide-stills/mob_kobold__9c7a3c.webp"
      },
      {
        "name": "Gleamfolk Pixie",
        "min": 15,
        "max": 16,
        "rare": false,
        "templateId": "mushroom_pixie",
        "model": "mob_kobold",
        "tint": "#d8c4f0",
        "still": "/guide-stills/mob_kobold__d8c4f0.webp"
      },
      {
        "name": "Sporeling Gatherer",
        "min": 15,
        "max": 15,
        "rare": false,
        "templateId": "sporeling_gatherer",
        "model": "mob_kobold",
        "tint": "#d8b98a",
        "still": "/guide-stills/mob_kobold__d8b98a.webp"
      },
      {
        "name": "Corrupted Sporeling",
        "min": 16,
        "max": 17,
        "rare": false,
        "templateId": "corrupted_sporeling",
        "model": "mob_kobold",
        "tint": "#5e4a72",
        "still": "/guide-stills/mob_kobold__5e4a72.webp"
      },
      {
        "name": "Fen Sprite",
        "min": 17,
        "max": 18,
        "rare": false,
        "templateId": "fen_sprite",
        "model": "mob_kobold",
        "tint": "#cfe0ea",
        "still": "/guide-stills/mob_kobold__cfe0ea.webp"
      },
      {
        "name": "Harvest Sprite",
        "min": 18,
        "max": 19,
        "rare": false,
        "templateId": "harvest_sprite",
        "model": "mob_kobold",
        "tint": "#e8c878",
        "still": "/guide-stills/mob_kobold__e8c878.webp"
      },
      {
        "name": "Willow Sprite",
        "min": 19,
        "max": 20,
        "rare": false,
        "templateId": "willow_sprite",
        "model": "mob_kobold",
        "tint": "#c8e0b8",
        "still": "/guide-stills/mob_kobold__c8e0b8.webp"
      },
      {
        "name": "Hedge Gnome",
        "min": 20,
        "max": 20,
        "rare": false,
        "templateId": "hedge_gnome",
        "model": "mob_kobold",
        "tint": "#5a8a46",
        "still": "/guide-stills/mob_kobold__5a8a46.webp"
      }
    ]
  },
  {
    "family": "humanoid",
    "creatures": [
      {
        "name": "Vale Bandit",
        "min": 3,
        "max": 5,
        "rare": false,
        "templateId": "vale_bandit",
        "model": "mob_bandit",
        "tint": "#6b3a32",
        "still": "/guide-stills/mob_bandit__6b3a32.webp"
      },
      {
        "name": "Gravecaller Cultist",
        "min": 10,
        "max": 12,
        "rare": false,
        "templateId": "gravecaller_cultist",
        "model": "mob_dark_caster",
        "tint": "#6c3483",
        "still": "/guide-stills/mob_dark_caster__6c3483.webp"
      },
      {
        "name": "Gravecaller Mender",
        "min": 11,
        "max": 12,
        "rare": false,
        "templateId": "gravecaller_mender",
        "model": "mob_bandit",
        "tint": "#6b3a32",
        "still": "/guide-stills/mob_bandit__6b3a32.webp"
      },
      {
        "name": "Gravecaller Summoner",
        "min": 11,
        "max": 12,
        "rare": false,
        "templateId": "gravecaller_summoner",
        "model": "mob_dark_caster",
        "tint": "#884ea0",
        "still": "/guide-stills/mob_dark_caster__884ea0.webp"
      },
      {
        "name": "Wyrmcult Zealot",
        "min": 17,
        "max": 19,
        "rare": false,
        "templateId": "wyrmcult_zealot",
        "model": "mob_bandit",
        "tint": "#6b3a32",
        "still": "/guide-stills/mob_bandit__6b3a32.webp"
      },
      {
        "name": "Wyrmcult Necromancer",
        "min": 18,
        "max": 19,
        "rare": false,
        "templateId": "wyrmcult_necromancer",
        "model": "mob_dark_caster",
        "tint": "#533566",
        "still": "/guide-stills/mob_dark_caster__533566.webp"
      },
      {
        "name": "Dawnhold Knight",
        "min": 20,
        "max": 20,
        "rare": false,
        "templateId": "hedge_knight",
        "model": "mob_bandit",
        "tint": "#6b3a32",
        "still": "/guide-stills/mob_bandit__6b3a32.webp"
      },
      {
        "name": "Downs Bandit",
        "min": 20,
        "max": 20,
        "rare": false,
        "templateId": "downs_bandit",
        "model": "mob_bandit",
        "tint": "#6b3a32",
        "still": "/guide-stills/mob_bandit__6b3a32.webp"
      },
      {
        "name": "Wreckfield Thief",
        "min": 20,
        "max": 20,
        "rare": false,
        "templateId": "wreck_thief",
        "model": "mob_bandit",
        "tint": "#6b3a32",
        "still": "/guide-stills/mob_bandit__6b3a32.webp"
      }
    ]
  },
  {
    "family": "troll",
    "creatures": [
      {
        "name": "Mirefen Troll",
        "min": 10,
        "max": 12,
        "rare": false,
        "templateId": "fen_troll",
        "model": "mob_troll",
        "tint": "#229954",
        "still": "/guide-stills/mob_troll__229954.webp"
      },
      {
        "name": "Grubjaw the Glutton",
        "min": 12,
        "max": 12,
        "rare": true,
        "templateId": "grubjaw",
        "model": "mob_troll",
        "tint": "#145a32",
        "still": "/guide-stills/mob_troll__145a32.webp"
      },
      {
        "name": "Dune Troll",
        "min": 17,
        "max": 19,
        "rare": false,
        "templateId": "dune_troll",
        "model": "mob_troll",
        "tint": "#b07040",
        "still": "/guide-stills/mob_troll__b07040.webp"
      }
    ]
  },
  {
    "family": "ogre",
    "creatures": [
      {
        "name": "Thornpeak Ogre",
        "min": 15,
        "max": 16,
        "rare": false,
        "templateId": "thornpeak_ogre",
        "model": "mob_ogre",
        "tint": "#9e7b53",
        "still": "/guide-stills/mob_ogre__9e7b53.webp"
      },
      {
        "name": "Gravenbark Shambler",
        "min": 20,
        "max": 20,
        "rare": false,
        "templateId": "gravenbark_shambler",
        "model": "mob_ogre",
        "tint": "#4e4a3a",
        "still": "/guide-stills/mob_ogre__4e4a3a.webp"
      }
    ]
  },
  {
    "family": "undead",
    "creatures": [
      {
        "name": "Restless Bones",
        "min": 5,
        "max": 7,
        "rare": false,
        "templateId": "restless_bones",
        "model": "skel_minion",
        "tint": "#d5dbdb",
        "still": "/guide-stills/skel_minion__d5dbdb.webp"
      },
      {
        "name": "Drowned Dead",
        "min": 9,
        "max": 11,
        "rare": false,
        "templateId": "drowned_dead",
        "model": "skel_minion",
        "tint": "#7fb3d5",
        "still": "/guide-stills/skel_minion__7fb3d5.webp"
      },
      {
        "name": "Drowned Votary",
        "min": 15,
        "max": 16,
        "rare": false,
        "templateId": "drowned_votary",
        "model": "skel_minion",
        "tint": "#6c8f8a",
        "still": "/guide-stills/skel_minion__6c8f8a.webp"
      },
      {
        "name": "Ashbone Raider",
        "min": 17,
        "max": 18,
        "rare": false,
        "templateId": "ashbone_raider",
        "model": "skel_minion",
        "tint": "#e8dcc8",
        "still": "/guide-stills/skel_minion__e8dcc8.webp"
      },
      {
        "name": "Ashbone Warcaller",
        "min": 18,
        "max": 19,
        "rare": false,
        "templateId": "ashbone_warcaller",
        "model": "skel_minion",
        "tint": "#d8c8a8",
        "still": "/guide-stills/skel_minion__d8c8a8.webp"
      },
      {
        "name": "Boneclad Revenant",
        "min": 18,
        "max": 19,
        "rare": false,
        "templateId": "boneclad_revenant",
        "model": "skel_warrior",
        "tint": "#cacfd2",
        "still": "/guide-stills/skel_warrior__cacfd2.webp"
      },
      {
        "name": "Barrow Wight",
        "min": 20,
        "max": 20,
        "rare": false,
        "templateId": "barrow_wight",
        "model": "skel_minion",
        "tint": "#9fb0c4",
        "still": "/guide-stills/skel_minion__9fb0c4.webp"
      },
      {
        "name": "Drowned Deckhand",
        "min": 20,
        "max": 20,
        "rare": false,
        "templateId": "drowned_deckhand",
        "model": "skel_minion",
        "tint": "#86988e",
        "still": "/guide-stills/skel_minion__86988e.webp"
      }
    ]
  },
  {
    "family": "elemental",
    "creatures": [
      {
        "name": "Duskwisp",
        "min": 15,
        "max": 16,
        "rare": false,
        "templateId": "duskwisp",
        "model": "mob_elemental",
        "tint": "#7a5f9e",
        "still": "/guide-stills/mob_elemental__7a5f9e.webp"
      },
      {
        "name": "Glimmerwisp",
        "min": 15,
        "max": 16,
        "rare": false,
        "templateId": "glimmerwisp",
        "model": "mob_elemental",
        "tint": "#ffc4ec",
        "still": "/guide-stills/mob_elemental__ffc4ec.webp"
      },
      {
        "name": "Ice Wisp",
        "min": 17,
        "max": 18,
        "rare": false,
        "templateId": "ice_wisp",
        "model": "mob_elemental",
        "tint": "#bfe4ff",
        "still": "/guide-stills/mob_elemental__bfe4ff.webp"
      },
      {
        "name": "Stormcrag Elemental",
        "min": 17,
        "max": 18,
        "rare": false,
        "templateId": "stormcrag_elemental",
        "model": "mob_elemental",
        "tint": "#5dade2",
        "still": "/guide-stills/mob_elemental__5dade2.webp"
      },
      {
        "name": "Rime Elemental",
        "min": 18,
        "max": 19,
        "rare": false,
        "templateId": "rime_elemental",
        "model": "mob_elemental",
        "tint": "#9fd0f0",
        "still": "/guide-stills/mob_elemental__9fd0f0.webp"
      },
      {
        "name": "Shardlord Kazzix",
        "min": 18,
        "max": 18,
        "rare": true,
        "templateId": "shardlord_kazzix",
        "model": "mob_elemental",
        "tint": "#aed6f1",
        "still": "/guide-stills/mob_elemental__aed6f1.webp"
      },
      {
        "name": "Lily Wisp",
        "min": 19,
        "max": 19,
        "rare": false,
        "templateId": "lily_wisp",
        "model": "mob_elemental",
        "tint": "#d0f2c8",
        "still": "/guide-stills/mob_elemental__d0f2c8.webp"
      },
      {
        "name": "Gale Wisp",
        "min": 20,
        "max": 20,
        "rare": false,
        "templateId": "gale_wisp",
        "model": "mob_elemental",
        "tint": "#bfe0e8",
        "still": "/guide-stills/mob_elemental__bfe0e8.webp"
      },
      {
        "name": "Nightkin Stargazer",
        "min": 20,
        "max": 20,
        "rare": false,
        "templateId": "nightkin_stargazer",
        "model": "mob_elemental",
        "tint": "#8fa8e0",
        "still": "/guide-stills/mob_elemental__8fa8e0.webp"
      },
      {
        "name": "Wood Wraith",
        "min": 20,
        "max": 20,
        "rare": false,
        "templateId": "wood_wraith",
        "model": "mob_elemental",
        "tint": "#9ab4a0",
        "still": "/guide-stills/mob_elemental__9ab4a0.webp"
      }
    ]
  },
  {
    "family": "dragonkin",
    "creatures": [
      {
        "name": "Sethrael the Palecoil",
        "min": 16,
        "max": 16,
        "rare": true,
        "templateId": "sethrael_palecoil",
        "model": "mob_dragonkin",
        "tint": "#bcd2e6",
        "still": "/guide-stills/mob_dragonkin__bcd2e6.webp"
      },
      {
        "name": "Dragonkin Broodguard",
        "min": 19,
        "max": 20,
        "rare": false,
        "templateId": "dragonkin_broodguard",
        "model": "mob_dragonkin",
        "tint": "#3e6b4f",
        "still": "/guide-stills/mob_dragonkin__3e6b4f.webp"
      }
    ]
  }
];

export const GUIDE_DELVES: GuideDelve[] = [
  {
    "id": "collapsed_reliquary",
    "name": "The Collapsed Reliquary",
    "theme": "crypt",
    "minLevel": 7,
    "suggestedPlayers": 2,
    "keeper": {
      "name": "Brother Halven",
      "title": "Reliquary Keeper"
    },
    "companion": {
      "name": "Acolyte Tessa",
      "role": "healer"
    },
    "tiers": [
      "Normal",
      "Heroic"
    ],
    "affixes": [
      "Restless Graves",
      "Bad Air",
      "Candleblind",
      "Grave Tax",
      "Unstable Roof",
      "Cult Remnants"
    ]
  }
];

export const GUIDE_MODELS: Record<string, GuideModelSpec> = {
  "player_warrior": {
    "url": "models/chars/players/knight.glb",
    "idle": "Idle",
    "height": 2.6,
    "show": [
      "Knight_Helmet",
      "Knight_Cape"
    ],
    "attach": [
      {
        "url": "models/weapons/sword_1handed.glb",
        "bone": "handslot.r"
      }
    ]
  },
  "player_paladin": {
    "url": "models/chars/players/paladin.glb",
    "idle": "Idle",
    "height": 2.6,
    "attach": [
      {
        "url": "models/weapons/axe_1handed.glb",
        "bone": "handslot.r"
      }
    ]
  },
  "player_hunter": {
    "url": "models/chars/players/ranger.glb",
    "idle": "Idle",
    "height": 2.6,
    "attach": [
      {
        "url": "models/weapons/crossbow_1handed.glb",
        "bone": "handslot.r"
      }
    ]
  },
  "player_rogue": {
    "url": "models/chars/players/rogue.glb",
    "idle": "Idle",
    "height": 2.6,
    "show": [
      "Rogue_Cape"
    ],
    "attach": [
      {
        "url": "models/weapons/dagger.glb",
        "bone": "handslot.r"
      },
      {
        "url": "models/weapons/dagger.glb",
        "bone": "handslot.l"
      }
    ]
  },
  "player_priest": {
    "url": "models/chars/players/mage.glb",
    "idle": "Idle",
    "height": 2.6,
    "show": [],
    "attach": [
      {
        "url": "models/weapons/staff.glb",
        "bone": "handslot.r"
      }
    ],
    "tintStrength": 0.5
  },
  "player_shaman": {
    "url": "models/chars/players/barbarian.glb",
    "idle": "Idle",
    "height": 2.6,
    "show": [
      "Barbarian_BearHat"
    ],
    "attach": [
      {
        "url": "models/weapons/axe_1handed.glb",
        "bone": "handslot.r"
      }
    ],
    "tintStrength": 0.4
  },
  "player_mage": {
    "url": "models/chars/players/mage.glb",
    "idle": "Idle",
    "height": 2.6,
    "show": [
      "Mage_Cape"
    ],
    "attach": [
      {
        "url": "models/weapons/staff.glb",
        "bone": "handslot.r"
      }
    ]
  },
  "player_warlock": {
    "url": "models/chars/players/mage.glb",
    "idle": "Idle",
    "height": 2.6,
    "show": [],
    "attach": [
      {
        "url": "models/weapons/wand.glb",
        "bone": "handslot.r"
      },
      {
        "url": "models/weapons/spellbook_open.glb",
        "bone": "handslot.l",
        "gripRef": "Spellbook_open"
      }
    ],
    "tintStrength": 0.45
  },
  "player_druid": {
    "url": "models/chars/players/druid.glb",
    "idle": "Idle",
    "height": 2.6,
    "attach": [
      {
        "url": "models/weapons/staff.glb",
        "bone": "handslot.r"
      }
    ]
  },
  "mob_demon": {
    "url": "models/creatures/demonalt.glb",
    "idle": "Idle",
    "height": 1.8,
    "tintStrength": 0.5
  },
  "mob_demonalt": {
    "url": "models/creatures/demonalt.glb",
    "idle": "Idle",
    "height": 2.1,
    "tintStrength": 0.35
  },
  "mob_wolf": {
    "url": "models/creatures/wolf.glb",
    "idle": "Idle",
    "height": 1.6,
    "tintStrength": 0.35
  },
  "mob_boar": {
    "url": "models/creatures/wild_boar.glb",
    "idle": "Idle1",
    "height": 1.45,
    "tintStrength": 0.4
  },
  "mob_spider": {
    "url": "models/creatures/spider.glb",
    "idle": "Spider_Idle",
    "height": 1.4,
    "tintStrength": 0.35
  },
  "mob_murloc": {
    "url": "models/creatures/frog.glb",
    "idle": "Idle",
    "height": 1.7,
    "tintStrength": 0.45
  },
  "mob_kobold": {
    "url": "models/creatures/goblin.glb",
    "idle": "Idle",
    "height": 2.1,
    "tintStrength": 0.2
  },
  "mob_bandit": {
    "url": "models/chars/players/rogue_hooded.glb",
    "idle": "Idle",
    "height": 2.6,
    "attach": [
      {
        "url": "models/weapons/dagger.glb",
        "bone": "handslot.r"
      },
      {
        "url": "models/weapons/dagger.glb",
        "bone": "handslot.l"
      }
    ],
    "tintStrength": 0.3
  },
  "skel_minion": {
    "url": "models/chars/enemies/skeleton_minion.glb",
    "idle": "Idle_Combat",
    "height": 2.5,
    "tintStrength": 0.25
  },
  "mob_troll": {
    "url": "models/creatures/orc.glb",
    "idle": "Idle",
    "height": 2.4,
    "tintStrength": 0.12
  },
  "mob_dark_caster": {
    "url": "models/chars/players/mage.glb",
    "idle": "Idle",
    "height": 2.6,
    "show": [
      "Mage_Hat"
    ],
    "attach": [
      {
        "url": "models/weapons/staff.glb",
        "bone": "handslot.r"
      }
    ],
    "tintStrength": 0.5
  },
  "mob_ogre": {
    "url": "models/creatures/giant.glb",
    "idle": "Idle",
    "height": 2.8,
    "tintStrength": 0.2
  },
  "mob_elemental": {
    "url": "models/creatures/golelingevolved.glb",
    "idle": "Flying_Idle",
    "height": 2.2,
    "hover": 0.3,
    "tintStrength": 0.4
  },
  "skel_warrior": {
    "url": "models/chars/enemies/skeleton_warrior.glb",
    "idle": "Idle_Combat",
    "height": 2.5,
    "tintStrength": 0.25
  },
  "mob_dragonkin": {
    "url": "models/creatures/dragonevolved.glb",
    "idle": "Flying_Idle",
    "height": 2.4,
    "hover": 0.25,
    "tintStrength": 0.2
  }
};
